---
services_path: "/home/{{ ansible_ssh_user | default(ansible_user_id) }}"
docker_install_compose_plugin: true
docker_install_compose: false
figurine_font: "3d.flf"

chewbacca_ip: 192.168.1.49
chewbacca_ip_tailscale: 100.110.122.14

luffy_ip: 192.168.1.217
luffy_ip_tailscale: 100.118.93.10

qnap_mac: 00:08:9B:EB:91:6C
qnap_ip: 192.168.1.131

rpi0_ip: 192.168.1.180
rpi2_ip: 192.168.1.57
rpi3_ip: 192.168.1.24
rpi4_ip: 192.168.1.173
rpi0_ip_tailscale: 100.107.148.90
rpi2_ip_tailscale: 100.88.184.43
rpi3_ip_tailscale: 100.95.2.1
rpi4_ip_tailscale: 100.74.114.39

sonoff_cam0_ip: 192.168.1.165
sonoff_cam1_ip: 192.168.1.226

ruckus_switch_ip: 192.168.1.50
ruckus_access_point_ip: 192.168.1.19

oci0_ip: 129.151.208.127
oci1_ip: 129.151.220.234
ocia1_ip: 129.151.195.184
oci0_ip_tailscale: 100.117.82.95
oci1_ip_tailscale: 100.99.164.134
ocia1_ip_tailscale: 100.99.34.15

gci0_ip: 34.67.225.162
gci0_ip_tailscale: 100.64.134.100

dns_overrides:
  - ip: "{{ chewbacca_ip }}"
    dns: "media.{{ domain }}"
  - ip: "{{ chewbacca_ip_tailscale }}"
    dns: "media.{{ domain }}"
  - ip: "{{ luffy_ip }}"
    dns: "{{ domain }}"
  - ip: "{{ luffy_ip_tailscale }}"
    dns: "{{ domain }}"

mqtt_server: "mqtt://{{ rpi4_ip }}"

router_href: http://192.168.1.1
pihole_primary_href: "http://{{ rpi3_ip }}/admin"
pihole_secondary_href: "http://{{ rpi2_ip }}/admin"
zigbee2mqtt_href: "http://{{ rpi0_ip }}:8080"
navidrome_href: "https://navidrome.media.{{ domain }}"
jellyfin_href: "https://jellyfin.media.{{ domain }}"
audiobookshelf_href: "https://audiobookshelf.{{ domain }}"
gatus0_href: "http://{{ oci0_ip_tailscale }}:8080"
gatus1_href: "http://{{ oci1_ip_tailscale }}:8080"
healthchecks0_href: "http://{{ oci0_ip_tailscale }}:8000"
healthchecks1_href: "http://{{ oci1_ip_tailscale }}:8000"

homeassistant_glances:
  - name: RPi4
    hostname: "{{ rpi4_ip }}"
    disk: "etc_hosts_"
  - name: RPi3
    hostname: "{{ rpi3_ip }}"
    disk: "etc_hosts_"
  - name: RPi2
    hostname: "{{ rpi2_ip }}"
    disk: "etc_hosts_"
  - name: RPi0
    hostname: "{{ rpi0_ip }}"
    disk: "etc_hosts_"
  - name: Chewbacca
    hostname: "{{ chewbacca_ip }}"
    disk: ""
  - name: OCI0
    hostname: "{{ oci0_ip_tailscale }}"
    disk: "etc_hosts_"
  - name: OCI1
    hostname: "{{ oci1_ip_tailscale }}"
    disk: "etc_hosts_"
  - name: OCIA1
    hostname: "{{ ocia1_ip_tailscale }}"
    disk: "etc_hosts_"
homeassistant_cli_server: "http://{{ rpi4_ip }}:8123"

smart_home_hosts:
  - name: rpi4
    ip: "{{ rpi4_ip }}"
    user: ubuntu
  - name: rpi3
    ip: "{{ rpi3_ip }}"
    user: manager
  - name: rpi2
    ip: "{{ rpi2_ip }}"
    user: manager
  - name: rpi0
    ip: "{{ rpi0_ip }}"
    user: serveradmin
  - name: chewbacca
    ip: "{{ chewbacca_ip }}"
    user: manager
  - name: luffy
    ip: "{{ luffy_ip }}"
    user: manager
  - name: oci0
    ip: "{{ oci0_ip }}"
    user: ubuntu
  - name: oci1
    ip: "{{ oci1_ip }}"
    user: ubuntu
  - name: ocia1
    ip: "{{ ocia1_ip }}"
    user: ubuntu
  - name: gci0
    ip: "{{ gci0_ip }}"
    user: hallstrom_claes
  - name: rpi4-tailscale
    ip: "{{ rpi4_ip_tailscale }}"
    user: ubuntu
  - name: rpi3-tailscale
    ip: "{{ rpi3_ip_tailscale }}"
    user: manager
  - name: rpi2-tailscale
    ip: "{{ rpi2_ip_tailscale }}"
    user: manager
  - name: rpi0-tailscale
    ip: "{{ rpi0_ip_tailscale }}"
    user: serveradmin
  - name: chewbacca-tailscale
    ip: "{{ chewbacca_ip_tailscale }}"
    user: manager
  - name: luffy-tailscale
    ip: "{{ luffy_ip_tailscale }}"
    user: manager
  - name: oci0-tailscale
    ip: "{{ oci0_ip_tailscale }}"
    user: ubuntu
  - name: oci1-tailscale
    ip: "{{ oci1_ip_tailscale }}"
    user: ubuntu
  - name: ocia1-tailscale
    ip: "{{ ocia1_ip_tailscale }}"
    user: ubuntu
  - name: gci0-tailscale
    ip: "{{ gci0_ip_tailscale }}"
    user: hallstrom_claes
