---
services_path: "/home/{{ ansible_ssh_user | default(ansible_user_id) }}"
docker_install_compose_plugin: true
docker_install_compose: false
figurine_font: "3d.flf"

chewbacca_ip: 192.168.1.49
chewbacca_ip_tailscale: 100.110.122.14

luffy_ip: 192.168.1.217
luffy_ip_tailscale: 100.118.93.10

qnap_mac: 00:08:9B:EB:91:6C
qnap_ip: 192.168.1.131

rpi0_ip: 192.168.1.180
rpi3_ip: 192.168.1.24
rpi4_ip: 192.168.1.173
rpi0_ip_tailscale: 100.107.148.90
rpi3_ip_tailscale: 100.95.2.1
rpi4_ip_tailscale: 100.74.114.39

sonoff_cam0_ip: 192.168.1.165
sonoff_cam1_ip: 192.168.1.226

ruckus_switch_ip: 192.168.1.50
ruckus_access_point_ip: 192.168.1.19

dns_overrides:
  - ip: "{{ chewbacca_ip }}"
    dns: "media.{{ domain }}"
  - ip: "{{ chewbacca_ip_tailscale }}"
    dns: "media.{{ domain }}"
  - ip: "{{ luffy_ip }}"
    dns: "{{ domain }}"
  - ip: "{{ luffy_ip_tailscale }}"
    dns: "{{ domain }}"

mqtt_server: "mqtt://{{ rpi4_ip }}"

router_href: http://192.168.1.1
zigbee2mqtt_href: "http://{{ rpi0_ip }}:8080"
navidrome_href: "https://navidrome.media.{{ domain }}"
jellyfin_href: "https://jellyfin.media.{{ domain }}"
audiobookshelf_href: "https://audiobookshelf.{{ domain }}"

homeassistant_glances:
  - name: RPi4
    hostname: "{{ rpi4_ip }}"
    disk: "etc_hosts_"
  - name: RPi3
    hostname: "{{ rpi3_ip }}"
    disk: "etc_hosts_"
  - name: RPi0
    hostname: "{{ rpi0_ip }}"
    disk: "etc_hosts_"
  - name: Chewbacca
    hostname: "{{ chewbacca_ip }}"
    disk: ""
  - name: Luffy
    hostname: "{{ luffy_ip }}"
    disk: ""

homeassistant_cli_server: "http://{{ rpi4_ip }}:8123"

smart_home_hosts:
  - name: rpi4
    ip: "{{ rpi4_ip }}"
    user: ubuntu
  - name: rpi3
    ip: "{{ rpi3_ip }}"
    user: manager
  - name: rpi0
    ip: "{{ rpi0_ip }}"
    user: serveradmin
  - name: chewbacca
    ip: "{{ chewbacca_ip }}"
    user: manager
  - name: luffy
    ip: "{{ luffy_ip }}"
    user: manager
  - name: rpi4-tailscale
    ip: "{{ rpi4_ip_tailscale }}"
    user: ubuntu
  - name: rpi3-tailscale
    ip: "{{ rpi3_ip_tailscale }}"
    user: manager
  - name: rpi0-tailscale
    ip: "{{ rpi0_ip_tailscale }}"
    user: serveradmin
  - name: chewbacca-tailscale
    ip: "{{ chewbacca_ip_tailscale }}"
    user: manager
  - name: luffy-tailscale
    ip: "{{ luffy_ip_tailscale }}"
    user: manager
