---
docker_users:
  - ubuntu
gatus_dns_endpoints:
  - name: "{{ domain }} (primary)"
    server: "{{ rpi3_ip_tailscale }}"
    query: "{{ domain }}"
    body: "{{ rpi4_ip }}"
  - name: "{{ domain }} (secondary) "
    server: "{{ rpi2_ip_tailscale }}"
    query: "{{ domain }}"
    body: "{{ rpi4_ip }}"
  - name: "media.{{ domain }} (primary)"
    server: "{{ rpi3_ip_tailscale }}"
    query: "media.{{ domain }}"
    body: "{{ chewbacca_ip }}"
  - name: "media.{{ domain }} (secondary)"
    server: "{{ rpi2_ip_tailscale }}"
    query: "media.{{ domain }}"
    body: "{{ chewbacca_ip }}"
gatus_external_endpoints:
  - name: Backup homeassistant
  - name: Backup zigbee2mqtt
  - name: Backup navidrome
  - name: Backup audiobookshelf
gatus_tailscale_devices_ignore:
  - "archlinux-msi"
  - "samsung SM-S906B"
