---
- alias: "Lights guest room off"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "on"
    to: "off"

  action:
    service: script.lights_guest_room_off


- alias: "Lights guest room on"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "off"
    to: "on"

  condition:
    condition: time
    before: input_datetime.lights_guest_room_off_evening

  action:
    service: script.lights_guest_room_on


- alias: "Lights guest room off time morning"
  use_blueprint:
    path: run_script_at.yaml
    input:
      datetime: input_datetime.lights_guest_room_off_morning
      script: script.lights_guest_room_off


- alias: "Lights guest room off time evening"
  use_blueprint:
    path: run_script_at.yaml
    input:
      datetime: input_datetime.lights_guest_room_off_evening
      script: script.lights_guest_room_off
