default:
  just --list

check:
  docker compose run autorestic autorestic check --verbose

backup LOCATION:
  docker compose run autorestic autorestic backup --verbose --location {{LOCATION}}

restore LOCATION BACKEND:
  docker compose run autorestic autorestic restore --verbose --location {{LOCATION}} --from {{BACKEND}} --to /data/{{LOCATION}}-restore

snapshots BACKEND:
  docker compose run autorestic autorestic exec --verbose --backend {{BACKEND}} -- snapshots
