---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "~/{{ service_name }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "~/{{ service_name }}/compose.yaml"
    mode: "0640"

- name: Create config files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ service_name }}/{{ item }}"
    mode: "0640"
  loop:
    - autorestic.yaml
    - rclone.conf
    - justfile
