---
services:
  mosquitto:
    container_name: mosquitto
    image: docker.io/eclipse-mosquitto:2.0.21
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Stockholm
    user: 1000:1000
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
