---
- alias: "Notify: Portfolio daily"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_daily

  condition:
    condition: state
    entity_id: binary_sensor.workday
    state: "on"

  action:
    - service: python_script.update_portfolio_state
    - service: python_script.notify_portfolio_state
      data:
        report: stock
        timespan: day

- alias: "Notify: Portfolio weekly"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_weekly

  condition:
    condition: time
    weekday:
      - sat

  action:
    - service: python_script.update_portfolio_state
    - service: python_script.notify_portfolio_state
      data:
        report: stock
        timespan: week

- alias: "Notify: Portfolio monthly"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_monthly

  condition:
    condition: template
    value_template: "{{ (now() + timedelta(days=1)).day == 1 }}"

  action:
    - service: python_script.update_portfolio_state
    - service: python_script.notify_portfolio_state
      data:
        report: stock
        timespan: month

- alias: "Notify: Portfolio dividend"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_dividend

  condition:
    condition: state
    entity_id: binary_sensor.workday
    state: "on"

  action:
    - service: python_script.notify_portfolio_dividend
      data:
        report: today

- alias: "Notify: Ping status"

  trigger:
    platform: state
    entity_id: group.ping

  action:
    service: python_script.notify_ping_state

- alias: "Notify: Garage door"

  trigger:
    platform: state
    entity_id: binary_sensor.garage_door

  action:
    service: python_script.notify_garage_door_state

- alias: "Notify: Garbage day"

  trigger:
    - platform: time
      at: "06:00"
    - platform: time
      at: "20:00"

  action:
    - service: python_script.notify_garbage_day

- alias: "Notify: GitHub Smart-Home failure"

  trigger:
    platform: state
    entity_id: sensor.github_smart_home
    to: failure

  action:
    service: notify.telegram
    data:
      message: GitHub Smart-Home workflow failed

- alias: "Notify: GitHub dotfiles failure"

  trigger:
    platform: state
    entity_id: sensor.github_dotfiles
    to: failure

  action:
    service: notify.telegram
    data:
      message: GitHub dotfiles workflow failed
