---
- alias: Blue tag triggered

  trigger:
    platform: tag
    tag_id: !secret nfc_blue_tag_id

  action:
    - service: tts.speak
      data:
        cache: true
        media_player_entity_id: media_player.sonos_beam
        message: "Hi from piper!"
      target:
        entity_id: tts.piper
