---
- name: Create service directory
  ansible.builtin.file:
    path: "{{ service_path }}"
    state: directory
    mode: "0775"

- name: Create data directory
  become: true
  ansible.builtin.file:
    path: "{{ service_path }}/data"
    state: directory
    mode: "0775"
    owner: 999
    group: 999

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create uWSGI config
  ansible.builtin.copy:
    src: "files/uwsgi.ini"
    dest: "{{ service_path }}/uwsgi.ini"
    mode: "0644"
  notify: "Recreate {{ service_name }}"
