---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"
    - "{{ service_path }}/log"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create middlewares
  ansible.builtin.copy:
    src: "files/middlewares.yaml"
    dest: "{{ service_path }}/middlewares.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.template:
    src: "templates/traefik.yaml.j2"
    dest: "{{ service_path }}/traefik.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create initial empty acme
  ansible.builtin.copy:
    content: ""
    dest: "{{ service_path }}/acme.json"
    force: false
    mode: "0600"

- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-passlib

- name: Create basic auth file
  community.general.htpasswd:
    path: "{{ service_path }}/.htpasswd"
    name: "{{ traefik_username }}"
    password: "{{ traefik_password }}"
    mode: "0600"
