---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - bash
    - exa
    - silversearcher-ag
    - vim

- name: Install and configure figurine
  ansible.builtin.include_role:
    name: ironicbadger.figurine
    apply:
      become: true

- name: Check if starship is already installed
  ansible.builtin.command: which starship
  failed_when: false
  changed_when: false
  check_mode: false
  register: bash_which_starship

- name: Download starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/install.sh
    mode: "0775"
  when: bash_which_starship.rc == 1

- name: Run starship install script
  become: true
  ansible.builtin.command: /tmp/install.sh --force
  changed_when: true
  when: bash_which_starship.rc == 1

- name: Create bashrc config
  ansible.builtin.copy:
    src: "files/bashrc"
    dest: ".bashrc"
    mode: "0640"

- name: Make it quiet when logging in through ssh
  ansible.builtin.copy:
    content: ""
    dest: ".hushlogin"
    mode: "0640"
