---
# yamllint disable rule:line-length
- binary_sensor:
    - name: Dark outside
      state: >
        {% set rising = state_attr("sun.sun", "rising") %}
        {% set elevation = states("sensor.sun_solar_elevation")|float %}
        {% set up = states("input_number.lights_sun_elevation_up")|float %}
        {% set down = states("input_number.lights_sun_elevation_down")|float %}
        {% set illuminance = states("sensor.illuminance_sma30") %}
        {% set illuminance_on = states("input_number.lights_illuminance_on")|float %}
        {% set illuminance_off = states("input_number.lights_illuminance_off")|float %}
        {% if is_number(illuminance) %}
          {% set illuminance = illuminance|float %}
          {% if rising %}
            {{ elevation < up and illuminance < illuminance_off }}
          {% else %}
            {{ elevation < down or illuminance < illuminance_on }}
          {% endif %}
        {% else %}
          {% if rising %}
            {{ elevation < up }}
          {% else %}
            {{ elevation < down }}
          {% endif %}
        {% endif %}
