---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Configure lovelace
lovelace: !include lovelace.yaml

# Setup an MQTT broker
mqtt: !include mqtt.yaml

# Configure the logger
logger: !include logger.yaml

# Configure the recorder
recorder: !include recorder.yaml

# Setup helpers
counter: !include helper/counter.yaml
input_boolean: !include helper/input_boolean.yaml
input_datetime: !include helper/input_datetime.yaml
input_number: !include helper/input_number.yaml
input_select: !include helper/input_select.yaml
input_text: !include helper/input_text.yaml
timer: !include helper/timer.yaml

# Setup notifiers
notify: !include notify.yaml
telegram_bot: !include telegram_bot.yaml

# Load sensors
sensor: !include_dir_merge_list sensor
template: !include_dir_merge_list template

# Load automations and scripts
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
python_script:
