---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Setup an MQTT broker
mqtt: !include mqtt.yaml

# Configure the logger
logger: !include logger.yaml

# Configure the recorder
recorder: !include recorder.yaml

# Setup helpers
counter: !include counter.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
timer: !include timer.yaml
