# yamllint disable rule:line-length
---
home_city: city
home_street: street
nixos_media_server_mac: 00:00:00:00:00:00
nixos_media_server_host: 0.0.0.0
ping_rpi3_ip: 0.0.0.0
ping_rpi4_ip: 0.0.0.0
sonoff_0_rtsp: rtsp://
sonoff_1_rtsp: rtsp://
telegram_api_key: telegram_api_key
telegram_chat_id: 9876543210
tradfri_shourtcut_button_0_device_id: 9876543210abcdef
tradfri_shourtcut_button_0_action_on: 0x00 action_on
tradfri_shourtcut_button_0_action_brightness_move_up: 0x00 action_brigthness_move_up
tradfri_shourtcut_button_0_action_brightness_stop: 0x00 action_brigthness_stop
xiaomi_wireless_switch_0_device_id: 9876543210abcdef
xiaomi_wireless_switch_0_discovery_id_action_single: 0x00 action_single
xiaomi_wireless_switch_0_discovery_id_action_double: 0x00 action_double
xiaomi_wireless_switch_0_discovery_id_action_hold: 0x00 action_hold
