{ config, pkgs, ... }:
let
  wallpaper = "${config.home.homeDirectory}/.local/share/brac.jpg";
  powerMenuScript = pkgs.writeShellScript "hypr-power-menu" ''
    printf 'Lock\nLogout\nReboot\nShutdown' | ${pkgs.fuzzel}/bin/fuzzel --dmenu --width 50 --minimal-lines | while read -r choice; do
      case "$choice" in
        Lock) hyprlock ;;
        Logout) hyprctl dispatch exit ;;
        Reboot) systemctl reboot ;;
        Shutdown) systemctl poweroff ;;
      esac
    done
  '';
in
{
  imports = [
    ../waybar
    ../fuzzel
  ];

  services.mako = {
    enable = true;
    settings = {
      background-color = "#00000080";
      border-color = "#e66100ff";
      border-radius = 4;
      border-size = 2;
      default-timeout = 5000;
      font = "JetBrains Mono 12";
    };
  };

  home = {
    packages = with pkgs; [
      brightnessctl
      wl-clipboard
      cliphist
      bibata-cursors
      libnotify
    ];
    file.".local/share/brac.jpg".source = ./brac.jpg;
    pointerCursor = {
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Ice";
      size = 24;
    };
  };

  # Disable home-manager's hyprland config generation
  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.unstable.hyprland;
    systemd.enable = false; # We handle autostart manually
  };

  # Write the Lua config file directly following wiki.hypr.land examples
  xdg.configFile."hypr/hyprland.lua".text =
    let
      mainMod = "SUPER";
      terminal = "wezterm";
      menu = "fuzzel";
      browser = "brave";
    in
    ''
      -- Hyprland Lua Config
      -- Generated by Home Manager
      -- See https://wiki.hypr.land/Configuring/Basics/

      ------------------
      ---- PROGRAMS ----
      ------------------

      local terminal = "${terminal}"
      local menu = "${menu}"
      local browser = "${browser}"

      ------------------
      ---- MONITORS ----
      ------------------

      hl.monitor({
        output = "",
        mode = "preferred",
        position = "auto",
        scale = 1.0,
      })

      ---------------------
      ---- AUTOSTART ----
      ---------------------

      hl.on("hyprland.start", function()
        hl.exec_cmd("${pkgs.waybar}/bin/waybar &")
        hl.exec_cmd("${pkgs.hyprpaper}/bin/hyprpaper &")
        hl.exec_cmd("${pkgs.hypridle}/bin/hypridle &")
        hl.exec_cmd("${pkgs.mako}/bin/mako &")
        hl.exec_cmd("${pkgs.wl-clipboard}/bin/wl-paste --watch ${pkgs.cliphist}/bin/cliphist store &")
        hl.exec_cmd("${pkgs.hyprlock}/bin/hyprlock &")
      end)

      -------------------
      ---- WORKSPACES ----
      -------------------

      hl.workspace_rule({ workspace = "1", monitor = "eDP-1" })
      hl.workspace_rule({ workspace = "2", monitor = "eDP-1" })
      hl.workspace_rule({ workspace = "3", monitor = "eDP-1" })
      hl.workspace_rule({ workspace = "4", monitor = "eDP-1" })
      hl.workspace_rule({ workspace = "5", monitor = "eDP-1" })
      hl.workspace_rule({ workspace = "6", monitor = "DP-1" })
      hl.workspace_rule({ workspace = "7", monitor = "DP-1" })
      hl.workspace_rule({ workspace = "8", monitor = "DP-1" })
      hl.workspace_rule({ workspace = "9", monitor = "DP-1" })

      -----------------------
      ---- LOOK AND FEEL ----
      -----------------------

      hl.config({
        general = {
          gaps_in = 5,
          gaps_out = 10,
          border_size = 2,
          col = {
            active_border = "rgb(e66100)",
            inactive_border = "rgba(e6610044)",
          },
          resize_on_border = false,
          allow_tearing = false,
          layout = "scrolling",
        },

        input = {
          kb_layout = "se",
          kb_options = "caps:none",
          follow_mouse = 0,
          sensitivity = 0,
          touchpad = {
            natural_scroll = false,
          },
        },

        scrolling = {
          fullscreen_on_one_column = true,
          column_width = 0.5,
          direction = "right",
        },

        decoration = {
          rounding = 4,
          rounding_power = 4,
        },

        binds = {
          hide_special_on_workspace_change = true,
        },

        cursor = {
          inactive_timeout = 1,
        },

        misc = {
          force_default_wallpaper = 0,
          disable_hyprland_logo = true,
          disable_splash_rendering = true,
        },
      })

      -----------------
      ---- RULES ----
      -----------------

      hl.window_rule({
        name = "borderless-tiling",
        match = { workspace = "w[t1]" },
        border_size = 0,
      })

      ----------------------
      ---- KEYBINDINGS ----
      ----------------------

      -- Basic window operations
      hl.bind("${mainMod} + F", hl.dsp.window.fullscreen())
      hl.bind("${mainMod} + T", hl.dsp.window.float({ action = "toggle" }))
      hl.bind("${mainMod} + Return", hl.dsp.exec_cmd(terminal))
      hl.bind("${mainMod} + SHIFT + Q", hl.dsp.window.close())
      hl.bind("${mainMod} + D", hl.dsp.exec_cmd(menu))
      hl.bind("${mainMod} + B", hl.dsp.exec_cmd(browser))
      hl.bind("${mainMod} + M", hl.dsp.exit())

      -- Focus movement
      hl.bind("${mainMod} + left", hl.dsp.focus({ direction = "left" }))
      hl.bind("${mainMod} + right", hl.dsp.focus({ direction = "right" }))
      hl.bind("${mainMod} + up", hl.dsp.focus({ direction = "up" }))
      hl.bind("${mainMod} + down", hl.dsp.focus({ direction = "down" }))

      -- Workspace navigation
      hl.bind("${mainMod} + Tab", hl.dsp.focus({ workspace = "e+1" }))
      hl.bind("${mainMod} + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
      hl.bind("${mainMod} + CTRL + Tab", hl.dsp.focus({ workspace = "previous" }))

      -- Special workspace
      hl.bind("${mainMod} + S", hl.dsp.workspace.toggle_special("scratchpad"))
      hl.bind("${mainMod} + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad" }))

      -- Lock and clipboard
      hl.bind("${mainMod} + L", hl.dsp.exec_cmd("hyprlock"))
      hl.bind("${mainMod} + V", hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu --width 100 | cliphist decode | wl-copy"))
      hl.bind("${mainMod} + SHIFT + P", hl.dsp.exec_cmd("${powerMenuScript}"))

      -- Workspace switching (1-9)
      for i = 1, 9 do
        hl.bind("${mainMod} + " .. i, hl.dsp.focus({ workspace = i }))
        hl.bind("${mainMod} + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
      end

      -- Mouse binds
      hl.bind("${mainMod} + ALT_L", hl.dsp.window.resize(), { mouse = true })

      -- Media keys
      hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"), { locked = true, repeating = true })
      hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"), { locked = true, repeating = true })
      hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
      hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
      hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%+"), { locked = true, repeating = true })
      hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%-"), { locked = true, repeating = true })

      -- Resize binds using hyprctl
      hl.bind("${mainMod} + ALT + right", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 5 0"), { repeating = true })
      hl.bind("${mainMod} + ALT + left", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -5 0"), { repeating = true })
      hl.bind("${mainMod} + ALT + up", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -5"), { repeating = true })
      hl.bind("${mainMod} + ALT + down", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 5"), { repeating = true })

      -- Systemd integration
      hl.on("hyprland.start", function()
        hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
      end)
    '';

  services.hyprpaper = {
    enable = true;
    settings = {
      splash = false;
      wallpaper = [
        {
          monitor = "eDP-1";
          path = wallpaper;
        }
      ];
    };
  };

  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        hide_cursor = true;
      };
      background = [
        {
          path = "${wallpaper}";
          blur_passes = 3;
          blur_size = 8;
        }
      ];
      input-field = {
        outer_color = "rgb(230, 97, 0)";
      };
    };
  };

  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };

      listener = [
        {
          timeout = 900;
          on-timeout = "hyprlock";
        }
        {
          timeout = 1200;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
      ];
    };
  };
}
