---
- platform: ping
  host: !secret ping_zigbee2mqtt_ip
  name: Ping Zigbee2Mqtt Host

- platform: ping
  host: !secret ping_mosquitto_ip
  name: Ping Mosquitto Host

- platform: ping
  host: !secret ping_info_screen_ip
  name: Ping Info Screen Host

- platform: ping
  host: !secret ping_qnap_ip
  name: Ping QNAP Host

- platform: ping
  host: !secret ping_buffalo_ip
  name: Ping Buffalo Host
