---
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.2
    container_name: uptimekuma
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
