---
- name: Setup pihole
  hosts: pihole
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: bash
      tags: never, init
    - role: docker_prune
      tags: never, init, docker_prune
    - role: pihole
      tags: pihole
    - role: netalertx
      tags: netalertx
    - role: duckdns
      tags: duckdns

- name: Setup smarthome
  hosts: smarthome
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: bash
      tags: never, init
    - role: docker_prune
      tags: never, init, docker_prune
    - role: mosquitto
      tags: mosquitto
    - role: homeassistant
      tags: homeassistant

- name: Setup zigbee
  hosts: zigbee
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: bash
      tags: never, init
    - role: docker_prune
      tags: never, init, docker_prune
    - role: zigbee2mqtt
      tags: zigbee2mqtt

- name: Setup localhost
  hosts: localhost
  vars_files:
    - vars/vault.yaml

  roles:
    - role: ssh_config
      tags: never, ssh_config
