---
- name: Setup pihole
  hosts: pihole
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: pihole
      tags: pihole
    - role: glances
      tags: glances
    - role: tailscale
      tags: tailscale

- name: Setup smarthome
  hosts: smarthome
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: speedtest
      tags: speedtest
    - role: duckdns
      tags: duckdns
    - role: dozzle
      tags: dozzle
    - role: glances
      tags: glances
    - role: tailscale
      tags: tailscale
    - role: mosquitto
      tags: mosquitto
    - role: traefik
      tags: traefik
    - role: homepage
      tags: homepage
    - role: homeassistant
      tags: homeassistant, autorestic
    - role: github_deploy
      tags: deploy

- name: Setup zigbee
  hosts: zigbee
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: zigbee2mqtt
      tags: zigbee2mqtt, autorestic
      vars:
        autorestic_docker: false
    - role: tailscale
      tags: tailscale
      vars:
        tailscale_docker: false

- name: Setup nixos
  hosts: nixos
  vars_files:
    - vars/vault.yaml

  roles:
    - role: nixos

- name: Setup localhost
  hosts: localhost
  vars_files:
    - vars/vault.yaml

  roles:
    - role: autorestic
      tags: never, autorestic
    - role: dashdot
      tags: never, dashdot
    - role: diun
      tags: never, diun
    - role: doku
      tags: never, doku
    - role: dozzle
      tags: never, dozzle
    - role: duckdns
      tags: never, duckdns
    - role: gatus
      tags: never, gatus
    - role: glances
      tags: never, glances
    - role: healthchecks
      tags: never, healthchecks
    - role: homeassistant
      tags: never, homeassistant
    - role: homepage
      tags: never, homepage
    - role: monocker
      tags: never, monocker
    - role: mosquitto
      tags: never, mosquitto
    - role: pihole
      tags: never, pihole
    - role: piper
      tags: never, piper
    - role: speedtest
      tags: never, speedtest
    - role: tailscale
      tags: never, tailscale
    - role: traefik
      tags: never, traefik
    - role: whisper
      tags: never, whisper
    - role: zigbee2mqtt
      tags: never, zigbee2mqtt
    - role: ssh_config
      tags: never, ssh_config

- name: Setup monitor
  hosts: monitor
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: tailscale
      tags: tailscale
    - role: healthchecks
      tags: healthchecks
    - role: gatus
      tags: gatus
    - role: glances
      tags: glances
    - role: dashdot
      tags: dashdot

- name: Setup ampere
  hosts: ampere
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: tailscale
      tags: tailscale
    - role: glances
      tags: glances
    - role: piper
      tags: piper
    - role: whisper
      tags: whisper
    - role: dashdot
      tags: dashdot
    - role: monocker
      tags: monocker
    - role: doku
      tags: doku
