---
- name: Setup pihole
  hosts: pihole
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: docker_compose_pihole
      tags: compose, pihole
    - role: glances
      tags: compose, glances
    - role: tailscale
      tags: compose, tailscale

- name: Setup smarthome
  hosts: smarthome
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: speedtest
      tags: compose, speedtest
    - role: duckdns
      tags: compose, duckdns
    - role: dozzle
      tags: compose, dozzle
    - role: diun
      tags: compose, diun
    - role: glances
      tags: compose, glances
    - role: tailscale
      tags: compose, tailscale
    - role: mosquitto
      tags: compose, mosquitto
    - role: docker_compose_traefik
      tags: compose, traefik
    - role: docker_compose_homepage
      tags: compose, homepage
    - role: autorestic
      tags: compose, autorestic
    - role: homeassistant
      tags: compose, homeassistant
    - role: github_deploy
      tags: deploy

- name: Setup zigbee
  hosts: zigbee
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: docker_compose_zigbee2mqtt
      tags: compose, zigbee2mqtt

- name: Setup nixos
  hosts: nixos
  vars_files:
    - vars/vault.yaml

  roles:
    - role: nixos

- name: Setup localhost
  hosts: localhost
  vars_files:
    - vars/vault.yaml

  roles:
    - role: autorestic
      tags: never, autorestic
    - role: dashdot
      tags: never, dashdot
    - role: diun
      tags: never, diun
    - role: dozzle
      tags: never, dozzle
    - role: duckdns
      tags: never, duckdns
    - role: gatus
      tags: never, gatus
    - role: glances
      tags: never, glances
    - role: homeassistant
      tags: never, homeassistant
    - role: docker_compose_homepage
      tags: never, homepage
    - role: mosquitto
      tags: never, mosquitto
    - role: docker_compose_pihole
      tags: never, pihole
    - role: piper
      tags: never, piper
    - role: speedtest
      tags: never, speedtest
    - role: tailscale
      tags: never, tailscale
    - role: docker_compose_traefik
      tags: never, traefik
    - role: uptimekuma
      tags: never, uptimekuma
    - role: whisper
      tags: never, whisper
    - role: docker_compose_zigbee2mqtt
      tags: never, zigbee2mqtt
    - role: ssh_config
      tags: never, ssh_config

- name: Setup monitor
  hosts: monitor
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: tailscale
      tags: compose, tailscale
    - role: gatus
      tags: compose, gatus
    - role: glances
      tags: compose, glances
    - role: dashdot
      tags: compose, dashdot

- name: Setup ampere
  hosts: ampere
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: tailscale
      tags: compose, tailscale
    - role: glances
      tags: compose, glances
    - role: piper
      tags: compose, piper
    - role: whisper
      tags: compose, whisper
    - role: dashdot
      tags: compose, dashdot
