---
homeassistant_service_name: "{{ ansible_role_name }}"
homeassistant_service_path: "{{ services_path }}/{{ homeassistant_service_name }}"  # yamllint disable rule:line-length
homeassistant_areas:
  - bedroom
  - guest_room
  - kitchen
  - living_room
  - laundry
  - master_bedroom
  - office

homeassistant_stocks: []
homeassistant_funds: []
homeassistant_glances: []
homeassistant_glances_used_sensors:
  - etc_hosts_used_percent
  - etc_hosts_used
  - etc_hosts_free
  - ram_used_percent
  - ram_used
  - ram_free
  - cpu_used
homeassistant_glances_unused_sensors:
  - etc_resolv_conf_used
  - etc_resolv_conf_used_percent
  - etc_resolv_conf_free
  - etc_hostname_used
  - etc_hostname_used_percent
  - etc_hostname_free
  - cpu_thermal_0_temperature
  - swap_used_percent
  - swap_used
  - swap_free
  - cpu_load
  - running
  - total
  - thread
  - sleeping
homeassistant_static_template_sensors:
  - name: Usage
    unit_of_measurement: "%"
    state: 0
  - name: Usage
    unit_of_measurement: "%"
    state: 100
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 0
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 40
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 0
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 100
