---
homeassistant_service_name: "{{ ansible_role_name }}"
homeassistant_service_path: "{{ services_path }}/{{ homeassistant_service_name }}"  # yamllint disable rule:line-length
homeassistant_areas:
  - guest_room
  - kitchen
  - living_room
  - laundry
  - master_bedroom
  - kids_bedroom
  - outdoor

homeassistant_stocks: []
homeassistant_funds: []
homeassistant_glances: []
homeassistant_glances_used_sensors:
  - DISK_used_percent
  - DISK_used
  - DISK_free
  - ram_used_percent
  - ram_used
  - ram_free
  - cpu_used
homeassistant_glances_unused_sensors:
  - etc_resolv_conf_used
  - etc_resolv_conf_used_percent
  - etc_resolv_conf_free
  - etc_hostname_used
  - etc_hostname_used_percent
  - etc_hostname_free
  - cpu_thermal_0_temperature
  - swap_used_percent
  - swap_used
  - swap_free
  - cpu_load
  - running
  - total
  - thread
  - sleeping
  - nix_store_used
  - nix_store_used_percent
  - nix_store_free
  - var_lib_docker_btrfs_used
  - var_lib_docker_btrfs_used_percent
  - var_lib_docker_btrfs_free
  - acpitz_1_temperature
  - core_0_temperature
  - nouveau_1_temperature
  - containers_active
  - containers_cpu_used
  - containers_ram_used
  - eth0_rx
  - eth0_tx
  - lo_rx
  - lo_tx
  - docker0_rx
  - docker0_tx
  - enp1s0_rx
  - enp1s0_tx
  - enp2s0_rx
  - enp2s0_tx
  - tailscale0_rx
  - tailscale0_tx
  - mmcblk0_disk_read
  - mmcblk0_disk_write
  - mmcblk0p1_disk_read
  - mmcblk0p1_disk_write
  - mmcblk0p2_disk_read
  - mmcblk0p2_disk_write
  - sda_disk_read
  - sda_disk_write
  - sda1_disk_read
  - sda1_disk_write
  - sda2_disk_read
  - sda2_disk_write
  - sda3_disk_read
  - sda3_disk_write
  - sda14_disk_read
  - sda14_disk_write
  - sda15_disk_read
  - sda15_disk_write
  - loop0_disk_read
  - loop0_disk_write
  - loop1_disk_read
  - loop1_disk_write
  - loop2_disk_read
  - loop2_disk_write
  - loop3_disk_read
  - loop3_disk_write
  - loop4_disk_read
  - loop4_disk_write
  - loop5_disk_read
  - loop5_disk_write
  - loop6_disk_read
  - loop6_disk_write
  - loop7_disk_read
  - loop7_disk_write

homeassistant_static_template_sensors:
  - name: Usage
    unit_of_measurement: "%"
    state: 0
  - name: Usage
    unit_of_measurement: "%"
    state: 100
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 0
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 40
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 0
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 100
