---
homeassistant_service_name: "{{ ansible_role_name }}"
homeassistant_service_path: "{{ services_path }}/{{ homeassistant_service_name }}"  # yamllint disable rule:line-length
homeassistant_areas:
  - guest_room
  - kitchen
  - living_room
  - laundry
  - master_bedroom
  - kids_bedroom
  - outdoor

homeassistant_stocks: []
homeassistant_funds: []
homeassistant_static_template_sensors:
  - name: Usage
    unit_of_measurement: "%"
    state: 0
  - name: Usage
    unit_of_measurement: "%"
    state: 100
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 0
  - name: Temperature
    unit_of_measurement: "°C"
    device_class: temperature
    state: 40
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 0
  - name: Humidity
    unit_of_measurement: "%"
    device_class: humidity
    state: 100
