---
services:
  tailscale:
    image: tailscale/tailscale:v1.40.1
    container_name: tailscaled
    network_mode: host
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    command: tailscaled
