---
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: docker.io/koenkk/zigbee2mqtt:v1.35.0
    platform: linux/arm/v6
    environment:
      - TZ=Europe/Stockholm
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - ./data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
