---
- platform: ping
  host: !secret ping_rpi0_ip
  name: Ping RPi0 Host

- platform: ping
  host: !secret ping_rpi2_ip
  name: Ping RPi2 Host

- platform: ping
  host: !secret ping_rpi3_ip
  name: Ping RPi3 Host

- platform: ping
  host: !secret ping_rpi4_ip
  name: Ping RPi4 Host
