---
services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:2023.05.2
    hostname: pihole
    environment:
      TZ: Europe/Stockholm
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
