---
services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:2025.02.4
    environment:
      TZ: Europe/Stockholm
      FTLCONF_webserver_api_password: pihole
      FTLCONF_webserver_domain: pihole.hallstrom.duckdns.org
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_misc_dnsmasq_lines: address=/hallstrom.duckdns.org/192.168.1.217;address=/hallstrom.duckdns.org/100.118.93.10  # yamllint disable rule:line-length
    security_opt:
      - no-new-privileges:true
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    volumes:
      - ./pihole:/etc/pihole
    restart: unless-stopped
