---
- name: Setup service
  ansible.builtin.include_role:
    name: service
  vars:
    service_name: "whisper"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"
    - "{{ service_path }}/data"

- name: Create compose file
  ansible.builtin.copy:
    src: "files/compose.yaml"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"
