---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "~/{{ service_name }}"
    - "~/{{ service_name }}/data"

- name: Create files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ service_name }}/{{ item }}"
    mode: "0640"
  loop:
    - compose.yaml
  notify: "Recreate {{ service_name }}"
