---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: piper
    docker_compose_service_sub_directories:
      - data
    docker_compose_service_file: true
