---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - ~/zigbee2mqtt
    - ~/zigbee2mqtt/data

- name: Create compose file
  ansible.builtin.copy:
    src: "files/compose.yaml"
    dest: "~/zigbee2mqtt/compose.yaml"
    mode: "0640"
  notify: Recreate zigbee2mqtt

- name: Create config
  ansible.builtin.template:
    src: "templates/configuration.yaml.j2"
    dest: "~/zigbee2mqtt/data/configuration.yaml"
    mode: "0640"
  notify: Recreate zigbee2mqtt

- name: Create devices and groups
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/zigbee2mqtt/data/{{ item }}"
    mode: "0400"
  loop:
    - devices.yaml
    - groups.yaml
  notify: Recreate zigbee2mqtt
