---
- alias: "Xiaomi Wirless Switch 0: Action single"

  trigger:
    - platform: device
      domain: mqtt
      device_id: !secret xiaomi_wireless_switch_0_device_id
      type: action
      subtype: single
      discovery_id: !secret xiaomi_wireless_switch_0_discovery_id_action_single

  action:
    - service: tts.speak
      data:
        cache: true
        media_player_entity_id: media_player.sonos_beam
        message: !secret bathroom_message
        language: sv_SE
        options:
          voice: "sv_SE-nst-medium"
      target:
        entity_id: tts.piper


- alias: "Xiaomi Wirless Switch 0: Action double"

  trigger:
    - platform: device
      domain: mqtt
      device_id: !secret xiaomi_wireless_switch_0_device_id
      type: action
      subtype: double
      discovery_id: !secret xiaomi_wireless_switch_0_discovery_id_action_double

  action:
    - service: script.lights_office_off

- alias: "Xiaomi Wirless Switch 0: Action hold"

  trigger:
    - platform: device
      domain: mqtt
      device_id: !secret xiaomi_wireless_switch_0_device_id
      type: action
      subtype: hold
      discovery_id: !secret xiaomi_wireless_switch_0_discovery_id_action_hold

  action:
    - service: script.lights_office_off

- alias: "TRADFRI Shortcut Button 0: Action on"

  trigger:
    - platform: device
      domain: mqtt
      device_id: !secret tradfri_shourtcut_button_0_device_id
      type: action
      subtype: "on"
      discovery_id: !secret tradfri_shourtcut_button_0_action_on

  action:
    - service: script.lights_master_bedroom_dim

- alias: "TRADFRI Shortcut Button 0: Action up"

  trigger:
    - platform: device
      domain: mqtt
      device_id: !secret tradfri_shourtcut_button_0_device_id
      type: action
      subtype: "brightness_stop"
      discovery_id: !secret tradfri_shourtcut_button_0_action_brightness_stop

  action:
    - service: script.lights_master_bedroom_on
