---
# yamllint disable rule:line-length
- alias: "Lights laundry dim"

  trigger:
    platform: template
    value_template: '{{ ((utcnow().strftime("%s") | int  + 3600) | timestamp_custom("%H:%M:%S")) == states.input_datetime.lights_laundry_off_evening.state }}'

  action:
    service: script.lights_laundry_dim


- alias: "Lights laundry on motion"

  trigger:
    platform: state
    entity_id: binary_sensor.xiaomi_movement_and_illuminance_0_occupancy
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.dark_outside
          state: "on"
        - condition: or
          conditions:
            - condition: time
              before: input_datetime.lights_laundry_off_morning
            - condition: time
              after: input_datetime.lights_laundry_off_evening

  action:
    service: script.lights_laundry_dim


- alias: "Lights laundry off motion"

  trigger:
    platform: state
    entity_id: binary_sensor.xiaomi_movement_and_illuminance_0_occupancy
    from: "on"
    to: "off"
    for:
      minutes: '{{ states("input_number.lights_laundry_timeout") | int }}'

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.dark_outside
          state: "on"
        - condition: or
          conditions:
            - condition: time
              before: input_datetime.lights_laundry_off_morning
            - condition: time
              after: input_datetime.lights_laundry_off_evening

  action:
    service: script.lights_laundry_off
