---
- alias: "Lights closet off"

  trigger:
    platform: state
    entity_id: binary_sensor.xiaomi_door_and_window_0_contact
    from: "on"
    to: "off"

  action:
    service: python_script.control_lights
    data:
      area: "closet"
      action: "off"


- alias: "Lights closet on"

  trigger:
    platform: state
    entity_id: binary_sensor.xiaomi_door_and_window_0_contact
    from: "off"
    to: "on"

  action:
    service: python_script.control_lights
    data:
      area: "closet"
      action: "on"
