---
# yamllint disable rule:line-length
- alias: "Lights master bedroom dim"

  trigger:
    platform: template
    value_template: '{{ ((utcnow().strftime("%s") | int  + 3600) | timestamp_custom("%H:%M:%S")) == states.input_datetime.lights_master_bedroom_off_evening.state }}'

  action:
    service: script.lights_master_bedroom_dim
