---
- alias: "Notify: Portfolio weekly"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_weekly

  condition:
    condition: time
    weekday:
      - sat

  action:
    - service: python_script.update_portfolio_state
    - service: python_script.notify_portfolio_state
      data:
        report: stock
        timespan: week
    - service: python_script.notify_portfolio_state
      data:
        report: fund
        timespan: week
    - service: python_script.notify_portfolio_state
      data:
        timespan: week

- alias: "Notify: Portfolio monthly"

  trigger:
    - platform: time
      at: input_datetime.notify_portfolio_monthly

  condition:
    condition: template
    value_template: "{{ (now() + timedelta(days=1)).day == 1 }}"

  action:
    - service: python_script.update_portfolio_state
    - service: python_script.notify_portfolio_state
      data:
        report: stock
        timespan: month
    - service: python_script.notify_portfolio_state
      data:
        report: fund
        timespan: month
    - service: python_script.notify_portfolio_state
      data:
        timespan: month
