---
- alias: "Telegram: Handle Commands"

  trigger:
    - platform: event
      event_type: telegram_command

  variables:
    command: "{{ trigger.event.data['command'] }}"

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ command == '/batteries' }}"
          sequence:
            - service: python_script.notify_batteries_state

        - conditions:
            - condition: template
              value_template: "{{ command == '/ping' }}"
          sequence:
            - service: python_script.notify_ping_state

        - conditions:
            - condition: template
              value_template: "{{ command == '/stock' }}"
          sequence:
            - service: python_script.notify_portfolio_state
              data:
                report: stock
                timespan: day

        - conditions:
            - condition: template
              value_template: "{{ command == '/fund' }}"
          sequence:
            - service: python_script.notify_portfolio_state
              data:
                report: fund
                timespan: day

        - conditions:
            - condition: template
              value_template: "{{ command == '/portfolio' }}"
          sequence:
            - service: python_script.notify_portfolio_state
              data:
                timespan: day

        - conditions:
            - condition: template
              value_template: "{{ command == '/dividend' }}"
          sequence:
            - service: python_script.notify_portfolio_dividend
