---
- name: Setup service
  ansible.builtin.include_role:
    name: service
  vars:
    service_name: "doku"

- name: Create directories
  ansible.builtin.file:
    path: "{{ service_path }}"
    state: directory
    mode: "0775"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"
