---
xiaomi_wireless_switch_0_room_light_ctrl:
  name: Xiaomi wireless switch 0 room light ctrl
  options:
    - Kitchen
    - Living Room
    - Bedroom
    - Guest Room
    - Master Bedroom
  icon: mdi:lightbulb-group
