---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - bash
    - exa
    - silversearcher-ag
    - vim

- name: Create bashrc config
  ansible.builtin.copy:
    src: "files/bashrc"
    dest: "~/.bashrc"
    mode: "0640"

- name: Make it quiet when logging in through ssh
  ansible.builtin.copy:
    content: ""
    dest: "~/.hushlogin"
    mode: "0640"
