---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"

- name: Create autorestic config
  ansible.builtin.template:
    src: "templates/autorestic.yaml.j2"
    dest: "{{ service_path }}/autorestic.yaml"
    mode: "0640"

- name: Create justfile
  ansible.builtin.copy:
    src: "files/justfile"
    dest: "{{ service_path }}/justfile"
    mode: "0640"

- name: Create periodic backup service
  when: autorestic_location is defined
  block:
    - name: Create backup script
      become: true
      ansible.builtin.template:
        src: autorestic_backup.sh.j2
        dest: "/usr/bin/autorestic_backup_{{ autorestic_location }}.sh"
        mode: "0755"

    - name: Create backup service file
      become: true
      ansible.builtin.template:
        src: autorestic_backup.service.j2
        dest: "/etc/systemd/system/autorestic_backup_{{ autorestic_location }}.service"  # yamllint disable-line rule:line-length
        mode: "0755"

    - name: Create backup timer file
      become: true
      ansible.builtin.template:
        src: autorestic_backup.timer.j2
        dest: "/etc/systemd/system/autorestic_backup_{{ autorestic_location }}.timer"  # yamllint disable-line rule:line-length
        mode: "0755"

    - name: Enable and start the backup timer
      become: true
      ansible.builtin.service:
        name: "autorestic_backup_{{ autorestic_location }}.timer"
        enabled: true
        state: started
