---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"

- name: Create autorestic config
  ansible.builtin.template:
    src: "templates/autorestic.yaml.j2"
    dest: "{{ service_path }}/autorestic.yaml"
    mode: "0640"

- name: Create justfile
  ansible.builtin.copy:
    src: "files/justfile"
    dest: "{{ service_path }}/justfile"
    mode: "0640"
