---
services:
  glances:
    image: nicolargo/glances:3.3.1.1-full
    container_name: glances
    pid: host
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=--webserver --disable-webui"
    restart: unless-stopped
