---
name: Setup ansible
descriptions: Install ansible and required roles/collections

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.x
    - name: Install ansible and required roles/collections
      shell: bash
      run: |
        pip install ansible
        ansible-galaxy install --role-file requirements.yaml

        echo "---
        b2_account_id: ci
        b2_account_key: ci
        backblaze_homeassistant_key: ci
        backblaze_zigbee2mqtt_key: ci
        domain: ci
        duckdns_domain: ci
        duckdns_token: ci
        healthchecks_backup_homeassistant_ping_url: ci
        healthchecks_backup_zigbee2mqtt_ping_url: ci
        healthchecks_secret_key: ci
        letsencrypt_email: ci
        letsencrypt_provider: ci
        mqtt_server: ci
        telegram_chatids: 0
        telegram_token: ci
        traefik_password: ci
        traefik_username: ci
        " > vars/vault.yaml
        sed -i '/vault_password_file/d' ansible.cfg
