---
name: Setup ansible
descriptions: Install ansible and required roles/collections

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.x
    - name: Install ansible and required roles/collections
      shell: bash
      run: |
        pip install ansible
        ansible-galaxy install --role-file requirements.yaml

        sed -i '/vars_files/I,+1 d' main.yaml
        sed -i '/vault_password_file/d' ansible.cfg
