---
- name: "Get entity {{ hass_cli_disable_entity_id }}"
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - hass-cli
      - --server
      - "{{ homeassistant_cli_server }}"
      - --token
      - "{{ homeassistant_cli_token }}"
      - --output
      - json
      - raw
      - ws
      - config/entity_registry/update
      - --json
      - ' {"entity_id":"{{ hass_cli_disable_entity_id }}"}'
  changed_when: false
  register: response

- name: "Disable entity {{ hass_cli_disable_entity_id }}"
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - hass-cli
      - --server
      - "{{ homeassistant_cli_server }}"
      - --token
      - "{{ homeassistant_cli_token }}"
      - --output
      - json
      - raw
      - ws
      - config/entity_registry/update
      - --json
      - ' {"entity_id":"{{ hass_cli_disable_entity_id }}", "disabled_by":"user"}'  # yamllint disable-line rule:line-length
  changed_when: true
  failed_when: hass_cli_disable_entity_check == true and response.stdout|from_json|json_query('success') == false  # yamllint disable-line rule:line-length
  when: response.stdout|from_json|json_query('result.entity_entry.disabled_by') != "user"  # yamllint disable-line rule:line-length
