---
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.13
    container_name: speedtest-tracker
    volumes:
      - ./config:/config
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${DOMAIN}`)
      - traefik.http.routers.speedtest.tls=true
      - traefik.http.routers.speedtest.service=speedtest
      - traefik.http.services.speedtest.loadbalancer.server.port=80
      - homepage.group=Monitor
      - homepage.name=Speedtest
      - homepage.icon=speedtest-tracker
      - homepage.href=https://speedtest.${DOMAIN}

networks:
  proxy:
    external: true
