---
version: '3.3'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.12
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
    restart: unless-stopped
