---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2021.6.2
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ./config:/config
    restart: always
