---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant:2021.5.0
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ./config:/config
    restart: always
