---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2022.12.1
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ./config:/config
    privileged: true
    restart: unless-stopped
