---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.3.3
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ./config:/config
    privileged: true
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}.duckdns.org`)
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.service=homeassistant
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
