---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant:2022.6.7
    environment:
      TZ: Europe/Stockholm
    network_mode: host
    volumes:
      - ./config:/config
    privileged: true
    restart: unless-stopped
