---
version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.07.1
    environment:
      TZ: Europe/Stockholm
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    volumes:
      - ./etc-pihole:/etc/pihole
    restart: unless-stopped
