---
lights_guest_room_on:
  alias: Lights guest room on
  description: Turn on all lights in the guest room
  sequence:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.tradfri_control_outlet_1
          - switch.shelly_plug_s_0


lights_guest_room_off:
  alias: Lights guest room off
  description: Turn off all lights in the guest room
  sequence:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.tradfri_control_outlet_1
          - switch.shelly_plug_s_0
