---
lights_guest_room_on:
  alias: Lights guest room on
  description: Turn on all lights in the guest room
  sequence:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.tradfri_control_outlet_1


lights_guest_room_off:
  alias: Lights guest room off
  description: Turn off all lights in the guest room
  sequence:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.tradfri_control_outlet_1


lights_guest_room_toggle:
  alias: Lights guest room toggle
  description: Toggle all lights in the guest room
  sequence:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.lights_guest_room
              state: "on"
          sequence:
            - service: script.lights_guest_room_off
        - conditions:
            - condition: state
              entity_id: binary_sensor.lights_guest_room
              state: "off"
          sequence:
            - service: script.lights_guest_room_on
