---
lights_laundry_on:
  alias: Lights laundry on
  description: Turn on all lights in the laundry
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_2
      data:
        brightness_pct: 10
        color_temp: 400
    - delay:
        seconds: 5
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_2
      data:
        transition: 10
        brightness_pct: 90


lights_laundry_dim:
  alias: Lights laundry dim
  description: Turn on all lights in the laundry dimmed
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_2
      data:
        transition: 10
        brightness_pct: 50


lights_laundry_off:
  alias: Lights laundry off
  description: Turn off all lights in the laundry
  sequence:
    - service: light.turn_off
      target:
        entity_id:
          - light.tradfri_bulb_2
      data:
        transition: 10
