---
lights_master_bedroom_on:
  alias: Lights master bedroom on
  description: Turn on all lights in the master bedroom
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_0
      data:
        brightness_pct: 10
        color_temp: 454
    - delay:
        seconds: 1
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_0
      data:
        transition: 10
        brightness_pct: 100


lights_master_bedroom_dim:
  alias: Lights master bedroom dim
  description: Turn on all lights in the master bedroom dimmed
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.tradfri_bulb_0
      data:
        transition: 10
        brightness_pct: 1


lights_master_bedroom_off:
  alias: Lights master bedroom off
  description: Turn off all lights in the master bedroom
  sequence:
    - service: light.turn_off
      target:
        entity_id:
          - light.tradfri_bulb_0
      data:
        transition: 10
