---
lights_kitchen_on:
  alias: Lights kitchen on
  description: Turn on all lights in the kitchen
  sequence:
    - service: switch.turn_on
      target:
        entity_id: switch.osram_smart_plug_1


lights_kitchen_off:
  alias: Lights kitchen off
  description: Turn off all lights in the kitchen
  sequence:
    - service: switch.turn_off
      target:
        entity_id: switch.osram_smart_plug_1


lights_kitchen_toggle:
  alias: Lights kitchen toggle
  description: Toggle all lights in the kitchen
  sequence:
    - service: switch.toggle
      target:
        entity_id: switch.osram_smart_plug_1
