---
version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    environment:
      TZ: Europe/Stockholm
    user: 1000:1000
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: always
