---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: homepage
    docker_compose_service_sub_directories:
      - config
    docker_compose_service_template: true
    docker_compose_service_extra_files:
      - config/bookmarks.yaml
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/widgets.yaml
    docker_compose_service_extra_templates:
      - config/services.yaml
