---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "~/{{ service_name }}"
    - "~/{{ service_name }}/config"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "~/{{ service_name }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ service_name }}/config/{{ item }}"
    mode: "0640"
  loop:
    - bookmarks.yaml
    - docker.yaml
    - kubernetes.yaml
    - settings.yaml
    - widgets.yaml
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.template:
    src: "templates/services.yaml.j2"
    dest: "~/{{ service_name }}/config/services.yaml"
    mode: "0640"
