---
services:
  traefik:
    image: docker.io/traefik:v2.10.0
    container_name: traefik
    networks:
      - proxy
    extra_hosts:
      - host.docker.internal:172.21.0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./middlewares.yaml:/etc/traefik/middlewares.yaml:ro
      - ./.htpasswd:/etc/traefik/.htpasswd:ro
      - ./acme.json:/etc/traefik/acme.json
      - ./log:/var/log/traefik
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.middlewares=auth@file,sslheader@file
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - homepage.group=Network
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=https://traefik.${DOMAIN}
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
