---
version: "3"
services:
  traefik:
    image: traefik:v2.8.1
    container_name: traefik
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./middlewares.yaml:/etc/traefik/middlewares.yaml:ro
      - ./.htpasswd:/etc/traefik/.htpasswd:ro
      - ./acme.json:/etc/traefik/acme.json
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}.duckdns.org`)
      - traefik.http.routers.traefik.middlewares=auth@file
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}.duckdns.org
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}.duckdns.org
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    name: proxy
