---
version: "3"
services:
  traefik:
    image: traefik:v2.8.1
    container_name: traefik
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./.htpasswd:/etc/traefik/.htpasswd
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.home`)
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/.htpasswd
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    name: proxy
