---
log:
  level: INFO
  filepath: /var/log/traefik/traefik.log
accessLog:
  filePath: /var/log/traefik/access.log
api:
  insecure: false
  dashboard: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: proxy
  file:
    filename: /etc/traefik/middlewares.yaml
    watch: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: hallstrom.claes@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: duckdns
