---
services:
  homepage:
    image: ghcr.io/benphelps/homepage:v0.6.16
    container_name: homepage
    environment:
      - TZ=Europe/Stockholm
      - HOMEPAGE_VAR_PIHOLE_HREF=${PIHOLE_HREF}
      - HOMEPAGE_VAR_ZIGBEE2MQTT_HREF=${ZIGBEE2MQTT_HREF}
      - HOMEPAGE_VAR_NAVIDROME_HREF=${NAVIDROME_HREF}
      - HOMEPAGE_VAR_JELLYFIN_HREF=${JELLYFIN_HREF}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}.duckdns.org`)
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
