---
- alias: "Telegram: Handle Event: Home Assistant updater"

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"

  action:
    - service: notify.telegram
      data_template:
        message: "
Home Assistant
{{ state_attr('binary_sensor.updater', 'newest_version') }}
released!


{{ state_attr('binary_sensor.updater', 'release_notes') }}
"
