---
- alias: "Lights living room off sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: input_number.lights_sun_elevation_up

  action:
    service: script.lights_living_room_off


- alias: "Lights living room off illuminance"

  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_movement_and_illuminance_0_illuminance
    above: input_number.lights_illuminance_off

  action:
    service: script.lights_living_room_off


- alias: "Lights living room on sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: input_number.lights_sun_elevation_down

  action:
    service: script.lights_living_room_on


- alias: "Lights living room on illuminance"

  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_movement_and_illuminance_0_illuminance
    below: input_number.lights_illuminance_on

  condition:
    condition: time
    before: input_datetime.lights_living_room_off

  action:
    service: script.lights_living_room_on


- alias: "Lights living room off time"

  trigger:
    platform: time
    at: input_datetime.lights_living_room_off

  action:
    service: script.lights_living_room_off


- alias: "Lights living room on off auto"

  trigger:
    platform: state
    entity_id: switch.osram_smart_plug_0
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.lights_auto_off_condition
          state: "on"

  action:
    service: script.lights_living_room_off
