---
- alias: "Lights kitchen off"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "on"
    to: "off"

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen on"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "off"
    to: "on"

  condition:
    condition: time
    before: input_datetime.lights_kitchen_off_evening

  action:
    service: script.lights_kitchen_on


- alias: "Lights kitchen off time"

  trigger:
    - platform: time
      at: input_datetime.lights_kitchen_off_morning
    - platform: time
      at: input_datetime.lights_kitchen_off_evening

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen off auto"

  trigger:
    platform: state
    entity_id: binary_sensor.lights_kitchen
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.dark_outside
          state: "off"

  action:
    service: script.lights_kitchen_off
