---
# yamllint disable rule:line-length
- alias: "Lights master bedroom off"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "on"
    to: "off"

  action:
    service: script.lights_master_bedroom_off


- alias: "Lights master bedroom on"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "off"
    to: "on"

  condition:
    condition: time
    before: input_datetime.lights_master_bedroom_off_evening

  action:
    service: script.lights_master_bedroom_on


- alias: "Lights master bedroom dim"

  trigger:
    platform: template
    value_template: '{{ ((utcnow().strftime("%s") | int  + 3600) | timestamp_custom("%H:%M:%S")) == states.input_datetime.lights_master_bedroom_off_evening.state }}'

  action:
    service: script.lights_master_bedroom_dim


- alias: "Lights master bedroom off time morning"
  use_blueprint:
    path: run_script_at.yaml
    input:
      datetime: input_datetime.lights_master_bedroom_off_morning
      script: script.lights_master_bedroom_off


- alias: "Lights master bedroom off time evening"
  use_blueprint:
    path: run_script_at.yaml
    input:
      datetime: input_datetime.lights_master_bedroom_off_evening
      script: script.lights_master_bedroom_off


- alias: "Lights master bedroom off auto"

  trigger:
    platform: state
    entity_id: binary_sensor.lights_master_bedroom
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.dark_outside
          state: "off"

  action:
    service: script.lights_master_bedroom_off
