---
- alias: "Lights kitchen off"

  trigger:
    platform: state
    entity_id: binary_sensor.lights_off_condition
    from: "off"
    to: "on"

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen on"

  trigger:
    platform: state
    entity_id: binary_sensor.lights_on_condition
    from: "off"
    to: "on"

  condition:
    condition: time
    before: input_datetime.lights_kitchen_off

  action:
    service: script.lights_kitchen_on


- alias: "Lights kitchen off time"

  trigger:
    platform: time
    at: input_datetime.lights_kitchen_off

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen off auto"

  trigger:
    platform: state
    entity_id: switch.osram_smart_plug_1
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.lights_auto_off_condition
          state: "on"

  action:
    service: script.lights_kitchen_off
