---
- alias: "Lights living room off"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "on"
    to: "off"

  action:
    service: script.lights_living_room_off


- alias: "Lights living room on"

  trigger:
    platform: state
    entity_id: binary_sensor.dark_outside
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: time
          before: input_datetime.lights_living_room_off_evening
        - condition: state
          entity_id: binary_sensor.watching_tv
          state: "off"

  action:
    service: script.lights_living_room_on


- alias: "Lights living room off time"

  trigger:
    - platform: time
      at: input_datetime.lights_living_room_off_morning
    - platform: time
      at: input_datetime.lights_living_room_off_evening

  action:
    service: script.lights_living_room_off


- alias: "Lights living room off auto"

  trigger:
    platform: state
    entity_id: binary_sensor.lights_living_room
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.dark_outside
          state: "off"

  action:
    service: script.lights_living_room_off


- alias: "Lights living room on tv"

  trigger:
    platform: state
    entity_id: binary_sensor.watching_tv
    from: "on"
    to: "off"

  condition:
    condition: and
    conditions:
      - condition: time
        after: input_datetime.lights_living_room_off_morning
      - condition: time
        before: input_datetime.lights_living_room_off_evening
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "on"

  action:
    service: script.lights_living_room_on


- alias: "Lights living room off tv"

  trigger:
    platform: state
    entity_id: binary_sensor.watching_tv
    from: "off"
    to: "on"

  action:
    service: script.lights_living_room_off
