---
- alias: "Lights kitchen off sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: input_number.lights_sun_elevation_up

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen on sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: input_number.lights_sun_elevation_down

  action:
    service: script.lights_kitchen_on


- alias: "Lights kitchen off time"

  trigger:
    platform: time
    at: input_datetime.lights_kitchen_off

  action:
    service: script.lights_kitchen_off


- alias: "Lights kitchen on off auto"

  trigger:
    platform: state
    entity_id: switch.osram_smart_plug_1
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.lights_auto_off
          state: "on"
        - condition: state
          entity_id: binary_sensor.lights_auto_off_condition
          state: "on"

  action:
    service: script.lights_kitchen_off
