---
- alias: "Lights kitchen off sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: input_number.lights_sun_elevation_up

  action:
    service: switch.turn_off
    target:
      entity_id: switch.osram_smart_plug_1


- alias: "Lights kitchen on sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: input_number.lights_sun_elevation_down

  action:
    service: switch.turn_on
    target:
      entity_id: switch.osram_smart_plug_1


- alias: "Lights kitchen off time"

  trigger:
    platform: time
    at: input_datetime.lights_kitchen_off

  action:
    service: switch.turn_off
    target:
      entity_id: switch.osram_smart_plug_1
