---
- alias: "Lights living room on sun"

  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: input_number.lights_sun_elevation_down

  action:
    service: switch.turn_on
    target:
      entity_id: switch.osram_smart_plug_0


- alias: "Lights living room off time"

  trigger:
    platform: time
    at: input_datetime.lights_living_room_off

  action:
    service: switch.turn_off
    target:
      entity_id: switch.osram_smart_plug_0
