---
- alias: "Telegram: Handle Commands"

  trigger:
    - platform: event
      event_type: telegram_command

  variables:
    command: "{{ trigger.event.data['command'] }}"

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ command == '/batteries' }}"
          sequence:
            - service: python_script.notify_batteries_state

        - conditions:
            - condition: template
              value_template: "{{ command == '/ping' }}"
          sequence:
            - service: python_script.notify_ping_state

        - conditions:
            - condition: template
              value_template: "{{ command == '/systemmonitor' }}"
          sequence:
            - service: python_script.notify_system_monitor_state
