---
- alias: "Telegram: Handle Command: systemmonitor"

  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: /systemmonitor

  action:
    - service: python_script.notify_system_monitor_state


- alias: "Telegram: Handle Command: batteries"

  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: /batteries

  action:
    - service: python_script.notify_batteries_state


- alias: "Telegram: Handle Command: ping"

  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: /ping

  action:
    - service: python_script.notify_ping_state
