---
- name: crazymax/diun
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^[\d+\.]+\d+$

- name: amir20/dozzle
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^v[\d+\.]+\d+$

- name: homeassistant/home-assistant
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^[\d+\.]+\d+$

- name: ghcr.io/benphelps/homepage
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^v[\d+\.]+\d+$

- name: eclipse-mosquitto
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^[\d+\.]+\d+$

- name: pihole/pihole
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^[\d+\.]+\d+$

- name: traefik
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^v[\d+\.]+\d+$

- name: koenkk/zigbee2mqtt
  watch_repo: true
  max_tags: 2
  sort_tags: semver
  include_tags:
    - ^[\d+\.]+\d+$
