---
services:
  whisper:
    image: docker.io/rhasspy/wyoming-whisper:0.0.3
    container_name: whisper
    ports:
      - 10300:10300
    volumes:
      - ./data:/data
    command: --model tiny-int8 --language en
    restart: unless-stopped
