---
water_leak_laundry:
  name: Water Leak Laundry
  entity_id: binary_sensor.xiaomi_water_leak_0
  state: "on"
  repeat: 5
  can_acknowledge: true
  notifiers:
    - ntfy

water_leak_kitchen:
  name: Water Leak Kitchen
  entity_id: binary_sensor.xiaomi_water_leak_1
  state: "on"
  repeat: 5
  can_acknowledge: true
  notifiers:
    - ntfy

water_leak_bathroom:
  name: Water Leak Bathroom
  entity_id: binary_sensor.xiaomi_water_leak_2
  state: "on"
  repeat: 5
  can_acknowledge: true
  notifiers:
    - ntfy
