---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: tailscale
    docker_compose_service_template: true
  when: tailscale_docker

- name: Install tailscale
  when: not tailscale_docker
  block:
    - name: Check if tailscale is already installed
      ansible.builtin.command: which tailscale
      failed_when: false
      changed_when: false
      check_mode: false
      register: tailscale_which_tailscale

    - name: Download tailscale install script
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/install.sh
        mode: "0775"
      when: tailscale_which_tailscale.rc == 1

    - name: Run tailscale install script
      become: true
      ansible.builtin.command: /tmp/install.sh
      changed_when: true
      when: tailscale_which_tailscale.rc == 1
