---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: zigbee2mqtt
    docker_compose_service_sub_directories:
      - data
    docker_compose_service_file: true
    docker_compose_service_extra_files:
      - data/devices.yaml
      - data/groups.yaml
    docker_compose_service_extra_templates:
      - data/configuration.yaml

- name: Create backups with autorestic
  ansible.builtin.include_role:
    name: autorestic
  vars:
    autorestic_location: "zigbee2mqtt"
    autorestic_docker: zigbee2mqtt_autorestic_docker
