---
- platform: min_max
  name: Illuminance
  type: mean
  entity_ids:
    - sensor.xiaomi_light_intensity_0
    - sensor.xiaomi_light_intensity_1

- platform: filter
  entity_id: sensor.illuminance
  name: "Illuminance (SMA30)"
  filters:
    filter: time_simple_moving_average
    window_size: "00:30"
