---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Setup http
http: !include http.yaml

# Configure lovelace
lovelace: !include lovelace.yaml

# Configure the logger
logger: !include logger.yaml

# Configure the recorder
recorder: !include recorder.yaml

# Setup helpers
counter: !include helper/counter.yaml
input_boolean: !include helper/input_boolean.yaml
input_datetime: !include helper/input_datetime.yaml
input_number: !include helper/input_number.yaml
input_select: !include helper/input_select.yaml
input_text: !include helper/input_text.yaml
timer: !include helper/timer.yaml

# Setup notifiers
notify: !include notify.yaml
telegram_bot: !include telegram_bot.yaml

# Load sensors
sensor: !include_dir_merge_list sensor
template: !include_dir_merge_list template
binary_sensor: !include_dir_merge_list binary_sensor

# Include switches
switch: !include_dir_merge_list switch

# Load automations and scripts
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
python_script:

# Setup alerts
alert: !include_dir_merge_named alert

# Configure groups
group: !include_dir_merge_named group

# Load cameras
camera: !include camera.yaml
