---
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.21.0.0/16
    - 192.168.1.0/24

logger:
  default: info

recorder:
  purge_keep_days: 3
  commit_interval: 30

input_datetime: !include helper/input_datetime.yaml
input_number: !include helper/input_number.yaml
sensor: !include_dir_merge_list sensor
template: !include_dir_merge_list template
automation: !include automations.yaml
automation yaml: !include_dir_merge_list automation
alert: !include_dir_merge_named alert
python_script:
