---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: speedtest
    docker_compose_service_sub_directories:
      - config
    docker_compose_service_template: true
