---
- name: Create flake
  ansible.builtin.copy:
    src: "files/flake.nix"
    dest: "/etc/nixos/flake.nix"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create config
  ansible.builtin.copy:
    src: "files/configuration.nix"
    dest: "/etc/nixos/configuration.nix"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create hardware config
  ansible.builtin.copy:
    src: "files/hardware-configuration.nix"
    dest: "/etc/nixos/hardware-configuration.nix"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create home config
  ansible.builtin.copy:
    src: "files/home.nix"
    dest: "/etc/nixos/home.nix"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create services folder
  ansible.builtin.file:
    path: "/etc/nixos/services"
    state: directory
    mode: "0755"

- name: Create services config
  ansible.builtin.copy:
    src: "files/services/"
    dest: "/etc/nixos/services"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create secrets folder
  ansible.builtin.file:
    path: "/etc/nixos/secrets"
    state: directory
    mode: "0755"

- name: Create secrets
  ansible.builtin.copy:
    src: "files/secrets/"
    dest: "/etc/nixos/secrets"
    mode: "0640"
  notify: "Rebuild nixos"

- name: Create autorestic config
  ansible.builtin.template:
    src: "templates/autorestic.yaml.j2"
    dest: "/etc/autorestic.yaml"
    mode: "0600"

- name: Create playlists
  ansible.builtin.copy:
    src: "files/claes-girls.json"
    dest: "/media/music/Claes\ Girls.nsp"
    mode: "0644"
