default:
    just --list

hostname := `hostname | cut -d "." -f 1`

switch flags="" flake=hostname:
    sudo nixos-rebuild switch --flake .#{{ flake }} {{ flags }}

update:
    nix flake update

gc:
    nix-collect-garbage -d
    nix-store --optimise
