---
http:
  routers:
    traefik:
      rule: "Host(`traefik.hallstrom.duckdns.org`)"
      service: api@internal

    homepage:
      rule: "Host(`homepage.hallstrom.duckdns.org`)"
      service: homepage

    audiobookshelf:
      rule: "Host(`audiobookshelf.hallstrom.duckdns.org`)"
      service: audiobookshelf

    navidrome:
      rule: "Host(`navidrome.hallstrom.duckdns.org`)"
      service: navidrome

    jellyfin:
      rule: "Host(`jellyfin.hallstrom.duckdns.org`)"
      service: jellyfin

    musicassistant:
      rule: "Host(`musicassistant.hallstrom.duckdns.org`)"
      service: musicassistant

    homeassistant:
      rule: "Host(`homeassistant.hallstrom.duckdns.org`)"
      service: homeassistant

    pihole:
      rule: "Host(`pihole.hallstrom.duckdns.org`)"
      middlewares:
        - sslheader
        - adminprefix
      service: pihole

    gatus:
      rule: "Host(`gatus.hallstrom.duckdns.org`)"
      service: gatus

    nextcloud:
      rule: "Host(`nextcloud.hallstrom.duckdns.org`)"
      service: nextcloud

  middlewares:
    sslheader:
      headers:
        customrequestheaders:
          X-Forwarded-Proto: https

    adminprefix:
      addPrefix:
        prefix: "/admin"

  services:
    homepage:
      loadbalancer:
        servers:
          - url: "http://0.0.0.0:8082"

    audiobookshelf:
      loadbalancer:
        servers:
          - url: "http://0.0.0.0:13378"

    navidrome:
      loadBalancer:
        servers:
          - url: "http://192.168.1.49:4533"

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://0.0.0.0:8096"

    musicassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.49:8095"

    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.173:8123"

    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.24"

    gatus:
      loadBalancer:
        servers:
          - url: "http://192.168.1.49:8080"

    nextcloud:
      loadbalancer:
        servers:
          - url: "http://0.0.0.0:8086"
