---
- name: "Create service directory for {{ docker_compose_service_name }}"
  ansible.builtin.file:
    path: "{{ services_path }}/{{ docker_compose_service_name }}"
    state: directory
    mode: "0775"

- name: "Create service sub directory for {{ docker_compose_service_name }}"
  ansible.builtin.file:
    path: "{{ services_path }}/{{ docker_compose_service_name }}/{{ item }}"
    state: directory
    mode: "0775"
  loop: "{{ docker_compose_service_sub_directories }}"
  when: docker_compose_service_sub_directories | length > 0

- name: "Template compose file for {{ docker_compose_service_name }}"
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ services_path }}/{{ docker_compose_service_name }}/compose.yaml"
    mode: "0644"
  notify: "Recreate {{ docker_compose_service_name }}"
  when: docker_compose_service_template

- name: "Copy compose file for {{ docker_compose_service_name }}"
  ansible.builtin.copy:
    src: "files/compose.yaml"
    dest: "{{ services_path }}/{{ docker_compose_service_name }}/compose.yaml"
    mode: "0644"
  notify: "Recreate {{ docker_compose_service_name }}"
  when: docker_compose_service_file

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
