---
version: '3'
services:
  tailscale:
    image: tailscale/tailscale:v1.36.0
    container_name: tailscaled
    privileged: true
    network_mode: host
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    command: tailscaled
