---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: mosquitto
    docker_compose_service_sub_directories:
      - config
      - data
      - log
    docker_compose_service_file: true
    docker_compose_service_extra_files:
      - config/mosquitto.conf
