---
- platform: rest
  resource: https://api.github.com/repos/claha/smart-home/actions/workflows/pre-commit.yaml/runs  # yamllint disable-line rule:line-length
  name: GitHub Smart-Home
  value_template: "{{ value_json['workflow_runs'][0]['conclusion'] }}"
  scan_interval: 60
- platform: rest
  resource: https://api.github.com/repos/claha/dotfiles/actions/workflows/pre-commit.yaml/runs  # yamllint disable-line rule:line-length
  name: GitHub dotfiles
  value_template: "{{ value_json['workflow_runs'][0]['conclusion'] }}"
  scan_interval: 60
