---
- platform: avanza_stock
  stock:
    - name: Currency USD/SEK
      id: 19000
    - name: Currency EUR/SEK
      id: 18998

    - name: Index OMX Stockholm 30
      id: 19002
      currency: points
    - name: Index OMX Stockholm 30 GI
      id: 1002994
      currency: points
    - name: Index OMX Stockholm PI
      id: 18988
      currency: points
    - name: Index OMX Stockholm GI
      id: 633079
      currency: points
