# shellcheck shell=bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Setup aliases
alias ls='exa'
alias ll='ls -la'

# Docker/Docker Compose aliases
alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\\t{{.Status}}\t{{.Names}}"'
alias dup='docker compose up --detach --force-recreate'
alias dlogs='docker compose logs --follow --tail 100'
alias dclean='docker system prune --all --volumes'

# Configure prompt
eval "$(starship init bash)"
