---
watch:
  workers: 1
  schedule: "0 11 * * *"
  firstCheckNotif: true
  runOnStartup: false

providers:
  file:
    filename: config.yaml

notif:
  telegram:
    templateBody: |
      {{ .Entry.Image.Path }} can now be updated to {{ .Entry.Image.Tag }}
      {{ if .Entry.Image.HubLink }}{{ .Entry.Image.HubLink }}{{ end }}
