---
- name: Setup pihole
  hosts: pihole
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: docker_compose_pihole
      tags: compose, pihole
    - role: docker_compose_glances
      tags: compose, glances
    - role: docker_compose_tailscale
      tags: compose, tailscale

- name: Setup smarthome
  hosts: smarthome
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: docker_compose_piper
      tags: compose, piper
    - role: docker_compose_speedtest
      tags: compose, speedtest
    - role: docker_compose_duckdns
      tags: compose, duckdns
    - role: docker_compose_dozzle
      tags: compose, dozzle
    - role: docker_compose_diun
      tags: compose, diun
    - role: docker_compose_glances
      tags: compose, glances
    - role: docker_compose_tailscale
      tags: compose, tailscale
    - role: docker_compose_mosquitto
      tags: compose, mosquitto
    - role: docker_compose_traefik
      tags: compose, traefik
    - role: docker_compose_homepage
      tags: compose, homepage

- name: Setup zigbee
  hosts: zigbee
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
      tags: never, init
    - role: bash
      tags: never, init
    - role: docker_compose_zigbee2mqtt
      tags: compose, zigbee2mqtt
