---
- name: Setup pihole
  hosts: pihole
  vars_files:
    - vars/vault.yaml

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - role: geerlingguy.docker
      become: true
    - role: docker_compose_pihole
    - role: docker_compose_glances
    - role: docker_compose_tailscale
