---
version: '3'
services:
  syncthing:
    image: linuxserver/syncthing:v1.18.0-ls57
    container_name: syncthing
    # hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
