---
- name: Create service file
  become: true
  ansible.builtin.copy:
    src: docker_prune.service
    dest: "/etc/systemd/system/docker_prune.service"
    mode: "0755"

- name: Create timer file
  become: true
  ansible.builtin.copy:
    src: docker_prune.timer
    dest: "/etc/systemd/system/docker_prune.timer"
    mode: "0755"

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start the timer
  become: true
  ansible.builtin.service:
    name: "docker_prune.timer"
    enabled: true
    state: started
