---
- Network:
    - Router:
        href: {{HOMEPAGE_VAR_ROUTER_HREF}}
        icon: asus-router
    - Pi-hole:
        href: {{HOMEPAGE_VAR_PIHOLE_HREF}}
        icon: pi-hole

- Smart Home:
    - Zigbee2Mqtt:
        href: {{HOMEPAGE_VAR_ZIGBEE2MQTT_HREF}}
        icon: zigbee2mqtt

- Media:
    - Navidrome:
        href: {{HOMEPAGE_VAR_NAVIDROME_HREF}}
        icon: navidrome
    - Jellyfin:
        href: {{HOMEPAGE_VAR_JELLYFIN_HREF}}
        icon: jellyfin

- Tailscale:
    - RPi4:
        icon: tailscale
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_RPI4}}
          key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
    - RPi3:
        icon: tailscale
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_RPI3}}
          key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
    - RPi2:
        icon: tailscale
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_RPI2}}
          key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
