---
- name: Create directories
  ansible.builtin.file:
    path: "~/{{ service_name }}"
    state: directory
    mode: "0775"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "~/{{ service_name }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"
