---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ homeassistant_service_path }}"
    - "{{ homeassistant_service_path }}/config"
    - "{{ homeassistant_service_path }}/config/custom_components"
    - "{{ homeassistant_service_path }}/config/custom_components/avanza_stock"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ homeassistant_service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create config
  ansible.builtin.copy:
    src: "files/config/"
    dest: "{{ homeassistant_service_path }}/config"
    mode: "0640"
    backup: true
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Download custom component avanza stock
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/custom-components/sensor.avanza_stock/v1.5.2/custom_components/avanza_stock/{{ item }}"  # yamllint disable rule:line-length
    dest: "{{ homeassistant_service_path }}/config/custom_components/avanza_stock/{{ item }}"  # yamllint disable rule:line-length
    mode: "0644"
  loop:
    - __init__.py
    - const.py
    - manifest.json
    - sensor.py

- name: Create input datetimes
  ansible.builtin.template:
    src: "templates/input_datetime.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/helper/input_datetime.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create lights timer automations
  ansible.builtin.template:
    src: "templates/lights_timer.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/automation/lights_timer.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create lights darkness automations
  ansible.builtin.template:
    src: "templates/lights_darkness.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/automation/lights_darkness.yaml"  # yamllint disable rule:line-length
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create portfolio
  ansible.builtin.template:
    src: "templates/portfolio.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/sensor/portfolio.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"
