---
- name: Setup service
  ansible.builtin.include_role:
    name: service
  vars:
    service_name: "homeassistant"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"
    - "{{ service_path }}/config"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.copy:
    src: "files/config/"
    dest: "{{ service_path }}/config"
    mode: "0640"
    backup: true
  notify: "Recreate {{ service_name }}"

- name: Create portfolio
  ansible.builtin.template:
    src: "templates/portfolio.yaml.j2"
    dest: "{{ service_path }}/config/sensor/portfolio.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create static template sensors
  ansible.builtin.template:
    src: "templates/static.yaml.j2"
    dest: "{{ service_path }}/config/template/static.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create monitor dashboard
  ansible.builtin.template:
    src: "templates/lovelace-monitor.yaml.j2"
    dest: "{{ service_path }}/config/lovelace-monitor.yaml"
    mode: "0640"

- name: Create secrets
  ansible.builtin.template:
    src: "templates/secrets.yaml.j2"
    dest: "{{ service_path }}/config/secrets.yaml"
    mode: "0600"
  notify: "Recreate {{ service_name }}"

- name: Create backups with autorestic
  ansible.builtin.include_role:
    name: autorestic
  vars:
    autorestic_location: "homeassistant"

- name: Hide stock entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.stock_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ homeassistant_stocks }}"

- name: Hide fund entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.fund_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ homeassistant_funds }}"

- name: Hide glances entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.{{ item.0.hostname | replace('.', '_') }}_{{ item.1 }}"  # yamllint disable rule:line-length
  with_nested:
    - "{{ homeassistant_glances }}"
    - "{{ homeassistant_glances_used_sensors }}"

- name: Disable glances entities
  ansible.builtin.include_role:
    name: hass_cli_disable_entity
  vars:
    hass_cli_disable_entity_id: "sensor.{{ item.0.hostname | replace('.', '_') }}_{{ item.1 }}"  # yamllint disable rule:line-length
  with_nested:
    - "{{ homeassistant_glances }}"
    - "{{ homeassistant_glances_unused_sensors }}"

- name: Hide static template entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.{{ item.name | lower }}_{{ item.state }}"
  loop: "{{ homeassistant_static_template_sensors }}"
