---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ homeassistant_service_path }}"
    - "{{ homeassistant_service_path }}/config"
    - "{{ homeassistant_service_path }}/config/custom_components"
    - "{{ homeassistant_service_path }}/config/custom_components/avanza_stock"
    - "{{ homeassistant_service_path }}/config/custom_components/tekniska_verken_garbage"  # yamllint disable rule:line-length

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ homeassistant_service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create config
  ansible.builtin.copy:
    src: "files/config/"
    dest: "{{ homeassistant_service_path }}/config"
    mode: "0640"
    backup: true
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Download custom component avanza stock
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/custom-components/sensor.avanza_stock/v1.5.0/custom_components/avanza_stock/{{ item }}"  # yamllint disable rule:line-length
    dest: "{{ homeassistant_service_path }}/config/custom_components/avanza_stock/{{ item }}"  # yamllint disable rule:line-length
    mode: "0644"
  loop:
    - __init__.py
    - const.py
    - manifest.json
    - sensor.py

- name: Download custom component tekniska verken garbage
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/custom-components/sensor.tekniska_verken_garbage/v1.0.0/custom_components/tekniska_verken_garbage/{{ item }}"  # yamllint disable rule:line-length
    dest: "{{ homeassistant_service_path }}/config/custom_components/tekniska_verken_garbage/{{ item }}"  # yamllint disable rule:line-length
    mode: "0644"
  loop:
    - __init__.py
    - manifest.json
    - sensor.py

- name: Create input datetimes
  ansible.builtin.template:
    src: "templates/input_datetime.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/helper/input_datetime.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create lights timer automations
  ansible.builtin.template:
    src: "templates/lights_timer.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/automation/lights_timer.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create lights darkness automations
  ansible.builtin.template:
    src: "templates/lights_darkness.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/automation/lights_darkness.yaml"  # yamllint disable rule:line-length
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create glances automations
  ansible.builtin.template:
    src: "templates/monitor.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/automation/monitor.yaml"  # yamllint disable rule:line-length
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create portfolio
  ansible.builtin.template:
    src: "templates/portfolio.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/sensor/portfolio.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create static template sensors
  ansible.builtin.template:
    src: "templates/static.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/template/static.yaml"
    mode: "0640"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create monitor dashboard
  ansible.builtin.template:
    src: "templates/lovelace-monitor.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/lovelace-monitor.yaml"
    mode: "0640"

- name: Create secrets
  ansible.builtin.template:
    src: "templates/secrets.yaml.j2"
    dest: "{{ homeassistant_service_path }}/config/secrets.yaml"
    mode: "0600"
  notify: "Recreate {{ homeassistant_service_name }}"

- name: Create backups with autorestic
  ansible.builtin.include_role:
    name: autorestic
  vars:
    autorestic_location: "homeassistant"

- name: Hide stock entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.stock_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ homeassistant_stocks }}"

- name: Hide fund entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.fund_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ homeassistant_funds }}"

- name: Hide glances entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.{{ item.0.hostname | replace('.', '_') }}_{{ item.1 | replace('DISK_', item.0.disk) }}"  # yamllint disable rule:line-length
  with_nested:
    - "{{ homeassistant_glances }}"
    - "{{ homeassistant_glances_used_sensors }}"

- name: Disable glances entities
  ansible.builtin.include_role:
    name: hass_cli_disable_entity
  vars:
    hass_cli_disable_entity_id: "sensor.{{ item.0.hostname | replace('.', '_') }}_{{ item.1 }}"  # yamllint disable rule:line-length
    hass_cli_disable_entity_check: false
  with_nested:
    - "{{ homeassistant_glances }}"
    - "{{ homeassistant_glances_unused_sensors }}"

- name: Hide static template entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.{{ item.name | lower }}_{{ item.state }}"
  loop: "{{ homeassistant_static_template_sensors }}"
