---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"
    - "{{ service_path }}/config"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.copy:
    src: "files/config/"
    dest: "{{ service_path }}/config"
    mode: "0640"
    backup: true
  notify: "Recreate {{ service_name }}"

- name: Create portfolio
  ansible.builtin.template:
    src: "templates/portfolio.yaml.j2"
    dest: "{{ service_path }}/config/sensor/portfolio.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create monitor dashboard
  ansible.builtin.template:
    src: "templates/lovelace-monitor.yaml.j2"
    dest: "{{ service_path }}/config/lovelace-monitor.yaml"
    mode: "0640"

- name: Create secrets
  ansible.builtin.template:
    src: "templates/secrets.yaml.j2"
    dest: "{{ service_path }}/config/secrets.yaml"
    mode: "0600"
  notify: "Recreate {{ service_name }}"

- name: Create backups with autorestic
  ansible.builtin.include_role:
    name: autorestic
  vars:
    autorestic_location: "homeassistant"

- name: Hide stock entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.stock_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ stocks }}"

- name: Hide fund entities
  ansible.builtin.include_role:
    name: hass_cli_hide_entity
  vars:
    hass_cli_hide_entity_id: "sensor.fund_{{ item.name | lower | replace(' ', '_') }}"  # yamllint disable rule:line-length
  loop: "{{ funds }}"
