---
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.30.2
    platform: linux/arm/v6
    environment:
      - TZ=Europe/Stockholm
    network_mode: host
    volumes:
      - ./data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
