---
- name: Setup service
  ansible.builtin.include_role:
    name: service
  vars:
    service_name: "gatus"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create config
  ansible.builtin.template:
    src: "templates/config.yaml.j2"
    dest: "{{ service_path }}/config.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"
