---
- name: Fetch list of tailscale devices
  delegate_to: localhost
  ansible.builtin.uri:
    url: "https://api.tailscale.com/api/v2/tailnet/-/devices"
    method: GET
    headers:
      Authorization: "Bearer {{ tailscale_key }}"
  register: gatus_tailscale_devices
  when: gatus_tailscale_devices is undefined

- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: gatus
    docker_compose_service_template: true
    docker_compose_service_extra_templates:
      - config.yaml
