---
- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: gatus
    docker_compose_service_template: true
    docker_compose_service_extra_templates:
      - config.yaml
