---
- name: Recreate {{ github_deploy_service_name }}
  ansible.builtin.command:
    chdir: "{{ github_deploy_service_path }}"
    cmd: docker compose up -d --force-recreate --build
  changed_when: true
