---
services:
  piper:
    image: docker.io/rhasspy/wyoming-piper:1.3.2
    container_name: piper
    ports:
      - 10200:10200
    volumes:
      - ./data:/data
    command: --voice en-us-lessac-low
    restart: unless-stopped
