---
name: Deploy autorestic

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/autorestic/**
      - .github/workflows/autorestic.yaml
  pull_request:
    paths:
      - roles/autorestic/**
      - .github/workflows/autorestic.yaml

jobs:
  autorestic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags autorestic \
          --extra-vars "b2_account_id=ci b2_account_key=ci \
          backblaze_homeassistant_key=ci \
          backblaze_zigbee2mqtt_key=ci \
          healthchecks_backup_homeassistant_url=ci \
          healthchecks_backup_zigbee2mqtt_url=ci"

          cd ~/autorestic && docker compose run autorestic
