---
name: Deploy autorestic

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/autorestic/**
      - .github/workflows/autorestic.yaml
  pull_request:
    paths:
      - roles/autorestic/**
      - .github/workflows/autorestic.yaml

jobs:
  autorestic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags autorestic

          cd ~/autorestic && docker compose run autorestic
