---
# yamllint disable rule:line-length
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: pre-commit/action@v2.0.0

  docker-compose:
    name: Validate docker-compose files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install docker-compose==1.27.4
          docker-compose --file homeassistant/docker-compose.yaml config --quiet
          docker-compose --file mosquitto/docker-compose.yaml config --quiet
          docker-compose --file syncthing/docker-compose.yaml config --quiet
          docker-compose --file zigbee2mqtt/docker-compose.yaml config --quiet
          docker-compose --file znc/docker-compose.yaml config --quiet

  home-assistant:
    name: Check home assistant configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker pull homeassistant/home-assistant:2021.7.1
      - run: |
          echo "---" > secrets.yaml
          echo "mqtt_broker: mqtt_broker" >> secrets.yaml
          echo "mqtt_username: mqtt_username" >> secrets.yaml
          echo "mqtt_password: mqtt_password" >> secrets.yaml
          echo "ping_info_screen_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_mosquitto_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_zigbee2mqtt_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_qnap_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_buffalo_ip: 0.0.0.0" >> secrets.yaml
          echo "telegram_api_key: telegram_api_key" >> secrets.yaml
          echo "telegram_chat_id: 9876543210" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_device_id: 9876543210abcdef" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_single: 0x00 action_single" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_double: 0x00 action_double" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_hold: 0x00 action_hold" >> secrets.yaml
          mv secrets.yaml homeassistant/config/secrets.yaml
      - run: |
          docker run --rm --volume $PWD/homeassistant/config:/config \
          homeassistant/home-assistant:2021.7.1 \
          hass --config /config --script check_config
