---
# yamllint disable rule:line-length
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0

  home-assistant:
    name: Check home assistant configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: |
          HA_TAG=$(grep image homeassistant/docker-compose.yaml | cut -d: -f3)
          docker pull homeassistant/home-assistant:$HA_TAG
          echo "---" > secrets.yaml
          echo "ping_info_screen_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_mosquitto_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_zigbee2mqtt_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_qnap_ip: 0.0.0.0" >> secrets.yaml
          echo "ping_buffalo_ip: 0.0.0.0" >> secrets.yaml
          echo "sonoff_0_rtsp: rtsp://" >> secrets.yaml
          echo "sonoff_1_rtsp: rtsp://" >> secrets.yaml
          echo "telegram_api_key: telegram_api_key" >> secrets.yaml
          echo "telegram_chat_id: 9876543210" >> secrets.yaml
          echo "tradfri_shourtcut_button_0_device_id: 9876543210abcdef" >> secrets.yaml
          echo "tradfri_shourtcut_button_0_action_on: 0x00 action_on" >> secrets.yaml
          echo "tradfri_shourtcut_button_0_action_brightness_move_up: 0x00 action_brigthness_move_up" >> secrets.yaml
          echo "tradfri_shourtcut_button_0_action_brightness_stop: 0x00 action_brigthness_stop" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_device_id: 9876543210abcdef" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_single: 0x00 action_single" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_double: 0x00 action_double" >> secrets.yaml
          echo "xiaomi_wireless_switch_0_discovery_id_action_hold: 0x00 action_hold" >> secrets.yaml
          mv secrets.yaml homeassistant/config/secrets.yaml
          docker run --rm --volume $PWD/homeassistant/config:/config \
          homeassistant/home-assistant:$HA_TAG \
          hass --config /config --script check_config
