---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: pre-commit/action@v2.0.0

  docker-compose:
    name: Validate docker-compose files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install docker-compose==1.27.4
          docker-compose --file homeassistant/docker-compose.yaml config --quiet
          docker-compose --file mosquitto/docker-compose.yaml config --quiet

  home-assistant:
    name: Check home assistant configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install homeassistant==2020.12.2
          hass -c homeassistant/config --script check_config
