---
name: Deploy dashdot

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/dashdot/**
      - .github/workflows/dashdot.yaml
  pull_request:
    paths:
      - roles/dashdot/**
      - .github/workflows/dashdot.yaml

jobs:
  dashdot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags dashdot

          docker ps --filter name=dashdot | grep --quiet dashdot
