---
name: Deploy diun

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/diun/**
      - .github/workflows/diun.yaml
  pull_request:
    paths:
      - roles/diun/**
      - .github/workflows/diun.yaml

jobs:
  diun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags diun

          docker ps --filter name=diun | grep --quiet diun
