---
name: Deploy doku

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/doku/**
      - .github/workflows/doku.yaml
  pull_request:
    paths:
      - roles/doku/**
      - .github/workflows/doku.yaml

jobs:
  doku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags doku

          docker ps --filter name=doku | grep --quiet doku
