---
name: Deploy dozzle

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/dozzle/**
      - .github/workflows/dozzle.yaml
  pull_request:
    paths:
      - roles/dozzle/**
      - .github/workflows/dozzle.yaml

jobs:
  dozzle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/setup-ansible
      - run: |
          docker network create --driver bridge proxy

          ansible-playbook main.yaml --limit localhost --tags dozzle

          docker ps --filter name=dozzle | grep --quiet dozzle
