---
name: Deploy dozzle

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/docker_compose_dozzle/**
      - .github/workflows/dozzle.yaml
  pull_request:
    paths:
      - roles/docker_compose_dozzle/**
      - .github/workflows/dozzle.yaml

jobs:
  dozzle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          docker network create --driver bridge proxy

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags dozzle \
          --extra-vars "domain=ci"

          docker ps --filter name=dozzle | grep --quiet dozzle
