---
name: Deploy duckdns

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/docker_compose_duckdns/**
      - .github/workflows/duckdns.yaml
  pull_request:
    paths:
      - roles/docker_compose_duckdns/**
      - .github/workflows/duckdns.yaml

jobs:
  duckdns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags duckdns \
          --extra-vars "duckdns_domain=ci duckdns_token=ci"

          docker ps --filter name=duckdns | grep --quiet duckdns
