---
name: Deploy duckdns

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/duckdns/**
      - .github/workflows/duckdns.yaml
  pull_request:
    paths:
      - roles/duckdns/**
      - .github/workflows/duckdns.yaml

jobs:
  duckdns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags duckdns

          docker ps --filter name=duckdns | grep --quiet duckdns
