---
name: Deploy glances

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/glances/**
      - .github/workflows/glances.yaml
  pull_request:
    paths:
      - roles/glances/**
      - .github/workflows/glances.yaml

jobs:
  glances:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags glances

          docker ps --filter name=glances | grep --quiet glances
