---
name: Deploy healthchecks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/healthchecks/**
      - .github/workflows/healthchecks.yaml
  pull_request:
    paths:
      - roles/healthchecks/**
      - .github/workflows/healthchecks.yaml

jobs:
  healthchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags healthchecks

          docker ps --filter name=healthchecks | grep --quiet healthchecks
