---
name: Deploy homepage

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/docker_compose_homepage/**
      - .github/workflows/homepage.yaml
  pull_request:
    paths:
      - roles/docker_compose_homepage/**
      - .github/workflows/homepage.yaml

jobs:
  homepage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          docker network create --driver bridge proxy

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags homepage \
          --extra-vars "domain=ci"

          docker ps --filter name=homepage | grep --quiet homepage
