---
name: Deploy homeassistant

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/homeassistant/**
      - .github/workflows/homeassistant.yaml
  pull_request:
    paths:
      - roles/homeassistant/**
      - .github/workflows/homeassistant.yaml

jobs:
  home-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags homeassistant

          docker ps --filter name=homeassistant | grep --quiet homeassistant
          docker exec homeassistant hass --config /config --script check_config
