---
name: Run home-assistant checks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/docker_compose_homeassistant/**
      - .github/workflows/home-assistant.yaml
  pull_request:
    paths:
      - roles/docker_compose_homeassistant/**
      - .github/workflows/home-assistant.yaml

jobs:
  home-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags homeassistant \
          --extra-vars "domain=ci"

          docker ps --filter name=homeassistant | grep --quiet homeassistant
          docker exec homeassistant hass --config /config --script check_config
