---
name: Deploy homepage

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/homepage/**
      - .github/workflows/homepage.yaml
  pull_request:
    paths:
      - roles/homepage/**
      - .github/workflows/homepage.yaml

jobs:
  homepage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          docker network create --driver bridge proxy

          ansible-playbook main.yaml --limit localhost --tags homepage

          docker ps --filter name=homepage | grep --quiet homepage
