---
name: Deploy homeassistant

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/homeassistant/**
      - .github/workflows/homeassistant.yaml
  pull_request:
    paths:
      - roles/homeassistant/**
      - .github/workflows/homeassistant.yaml

jobs:
  home-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags homeassistant \
          --extra-vars "domain=ci b2_account_id=ci b2_account_key=ci \
          backblaze_homeassistant_key=ci backblaze_zigbee2mqtt_key=ci \
          healthchecks_backup_homeassistant_url=ci \
          healthchecks_backup_zigbee2mqtt_url=ci"

          docker ps --filter name=homeassistant | grep --quiet homeassistant
          docker exec homeassistant hass --config /config --script check_config
