---
name: Deploy mosquitto

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/mosquitto/**
      - .github/workflows/mosquitto.yaml
  pull_request:
    paths:
      - roles/mosquitto/**
      - .github/workflows/mosquitto.yaml

jobs:
  mosquitto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags mosquitto

          docker ps --filter name=mosquitto | grep --quiet mosquitto
