---
name: Deploy pihole

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/docker_compose_pihole/**
      - .github/workflows/pihole.yaml
  pull_request:
    paths:
      - roles/docker_compose_pihole/**
      - .github/workflows/pihole.yaml

jobs:
  pihole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          sudo apt update
          sudo apt install resolvconf -y

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml

          # sudo systemctl disable systemd-resolved
          # sudo systemctl stop systemd-resolved

          ansible-playbook main.yaml --limit localhost --tags pihole -vv

          docker ps --filter name=pihole | grep --quiet pihole
