---
name: Deploy piper

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/piper/**
      - .github/workflows/piper.yaml
  pull_request:
    paths:
      - roles/piper/**
      - .github/workflows/piper.yaml

jobs:
  piper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags piper

          docker ps --filter name=piper | grep --quiet piper
