---
# yamllint disable rule:line-length
name: Run pre-commit hooks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          sh install-opentofu.sh --install-method deb
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x
      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg
      - uses: pre-commit/action@v3.0.1
