---
name: Run pre-commit hooks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.x
      - run: |
          sed -i '/vars_files/I,+1 d' ansible/main.yaml
          sed -i '/vault_password_file/d' ansible/ansible.cfg
      - uses: pre-commit/action@v3.0.0
