---
name: Deploy speedtest

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/speedtest/**
      - .github/workflows/speedtest.yaml
  pull_request:
    paths:
      - roles/speedtest/**
      - .github/workflows/speedtest.yaml

jobs:
  speedtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          docker network create --driver bridge proxy

          ansible-playbook main.yaml --limit localhost --tags speedtest

          docker ps --filter name=speedtest | grep --quiet speedtest
