---
name: Deploy tailscale

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/tailscale/**
      - .github/workflows/tailscale.yaml
  pull_request:
    paths:
      - roles/tailscale/**
      - .github/workflows/tailscale.yaml

jobs:
  tailscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags tailscale

          docker ps --filter name=tailscale | grep --quiet tailscale
