---
name: Deploy traefik

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml
  pull_request:
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml

jobs:
  traefik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags traefik

          docker ps --filter name=traefik | grep --quiet traefik
