---
name: Deploy traefik

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml
  pull_request:
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml

jobs:
  traefik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags traefik \
          --extra-vars "domain=ci duckdns_token=ci \
          traefik_username=ci traefik_password=ci \
          letsencrypt_email=ci letsencrypt_provider=ci"

          docker ps --filter name=traefik | grep --quiet traefik
