---
name: Deploy traefik

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml
  pull_request:
    paths:
      - roles/traefik/**
      - .github/workflows/traefik.yaml

jobs:
  traefik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags traefik \
          --extra-vars "domain=ci duckdns_token=ci \
          traefik_username=ci traefik_password=ci \
          letsencrypt_email=ci letsencrypt_provider=ci"

          docker ps --filter name=traefik | grep --quiet traefik
