---
name: Deploy uptimekuma

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/uptimekuma/**
      - .github/workflows/uptimekuma.yaml
  pull_request:
    paths:
      - roles/uptimekuma/**
      - .github/workflows/uptimekuma.yaml

jobs:
  uptimekuma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags uptimekuma

          docker ps --filter name=uptimekuma | grep --quiet uptimekuma
