---
name: Deploy whisper

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/whisper/**
      - .github/workflows/whisper.yaml
  pull_request:
    paths:
      - roles/whisper/**
      - .github/workflows/whisper.yaml

jobs:
  whisper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./.github/actions/setup-ansible
      - run: |
          ansible-playbook main.yaml --limit localhost --tags whisper

          docker ps --filter name=whisper | grep --quiet whisper
