---
# yamllint disable rule:line-length
name: Deploy zigbee2mqtt

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/zigbee2mqtt/**
      - .github/workflows/zigbee2mqtt.yaml
  pull_request:
    paths:
      - roles/zigbee2mqtt/**
      - .github/workflows/zigbee2mqtt.yaml

jobs:
  zigbee2mqtt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x

      - run: |
          sed -i '/vars_files/I,+1 d' main.yaml
          sed -i '/vault_password_file/d' ansible.cfg

          sed -i '/devices/I,+1 d' roles/zigbee2mqtt/files/compose.yaml
          sed -i '/platform/d' roles/zigbee2mqtt/files/compose.yaml

          pip install ansible
          ansible-galaxy install --role-file requirements.yaml
          ansible-playbook main.yaml --limit localhost --tags zigbee2mqtt \
          --extra-vars "mqtt_server=ci"

          docker ps --filter name=zigbee2mqtt | grep --quiet zigbee2mqtt
