---
# yamllint disable rule:line-length
name: Deploy zigbee2mqtt

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - roles/zigbee2mqtt/**
      - .github/workflows/zigbee2mqtt.yaml
  pull_request:
    paths:
      - roles/zigbee2mqtt/**
      - .github/workflows/zigbee2mqtt.yaml

jobs:
  zigbee2mqtt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/setup-ansible
      - run: |
          sed -i '/devices/I,+1 d' roles/zigbee2mqtt/files/compose.yaml
          sed -i '/platform/d' roles/zigbee2mqtt/files/compose.yaml

          ansible-playbook main.yaml --limit localhost --tags zigbee2mqtt \
          --extra-vars "mqtt_server=ci b2_account_id=ci b2_account_key=ci \
          backblaze_homeassistant_key=ci backblaze_zigbee2mqtt_key=ci \
          healthchecks_backup_homeassistant_url=ci"

          docker ps --filter name=zigbee2mqtt | grep --quiet zigbee2mqtt
