---
- name: Check if resolvconf is used
  ansible.builtin.command: which resolvconf
  failed_when: false
  changed_when: false
  check_mode: false
  register: pihole_which_resolvconf

- name: Use local nameserver
  ansible.builtin.lineinfile:
    line: "name_serves=127.0.0.1"
    dest: /etc/resolvconf.conf
    regexp: "^#?name_servers="
  become: true
  notify: Update resolvconf
  when: pihole_which_resolvconf.rc == 0

- name: Setup service
  ansible.builtin.include_role:
    name: service
  vars:
    service_name: "pihole"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ service_path }}"
    - "{{ service_path }}/etc-pihole"
    - "{{ service_path }}/etc-dnsmasq.d"

- name: Create compose file
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ service_path }}/{{ item }}"
    mode: "0640"
  loop:
    - compose.yaml
  notify: "Recreate {{ service_name }}"

- name: Create adlists
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ service_path }}/etc-pihole/{{ item }}"
    mode: "0640"
  loop:
    - adlists.list
  notify: "Recreate {{ service_name }}"

- name: Create dns overrides
  ansible.builtin.template:
    src: "templates/03-dns-overrides.conf.j2"
    dest: "{{ service_path }}/etc-dnsmasq.d/03-dns-overrides.conf"
    mode: "0640"
  notify: "Recreate {{ service_name }}"
