---
- name: Check if resolvconf is used
  ansible.builtin.command: which resolvconf
  failed_when: false
  changed_when: false
  check_mode: false
  register: pihole_which_resolvconf

- name: Use local nameserver
  ansible.builtin.lineinfile:
    line: "name_serves=127.0.0.1"
    dest: /etc/resolvconf.conf
    regexp: "^#?name_servers="
  become: true
  notify: Update resolvconf
  when: pihole_which_resolvconf.rc == 0

- name: Create docker compose service
  ansible.builtin.include_role:
    name: docker_compose_service
  vars:
    docker_compose_service_name: pihole
    docker_compose_service_sub_directories:
      - pihole
    docker_compose_service_file: true
    docker_compose_service_extra_files:
      - pihole/adlists.list
