---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "~/{{ service_name }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "~/{{ service_name }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ service_name }}"

- name: Create files for image
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ service_name }}/{{ item }}"
    mode: "0640"
  loop:
    - Dockerfile
    - .dockerignore
    - main.py
  notify: "Recreate {{ service_name }}"

- name: Create initial empty processed_runs.txt
  ansible.builtin.copy:
    content: ""
    dest: "~/{{ service_name }}/processed_runs.txt"
    force: false
    mode: "0600"
