---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ github_deploy_service_path }}"

- name: Create compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "{{ github_deploy_service_path }}/compose.yaml"
    mode: "0640"
  notify: "Recreate {{ github_deploy_service_name }}"

- name: Create files for image
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ github_deploy_service_path }}/"
    mode: "0640"
  notify: "Recreate {{ github_deploy_service_name }}"

- name: Create initial empty processed_runs.txt
  ansible.builtin.copy:
    content: ""
    dest: "{{ github_deploy_service_path }}/processed_runs.txt"
    force: false
    mode: "0600"
