---
version: "3.8"
services:
  autorestic:
    image: cupcakearmy/autorestic:1.7.4
    container_name: autorestic
    volumes:
      - ../:/data
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro
    environment:
      - AUTORESTIC_BACKBLAZE_B2_ACCOUNT_ID=${B2_ACCOUNT_ID}
      - AUTORESTIC_BACKBLAZE_B2_ACCOUNT_KEY=${B2_ACCOUNT_KEY}
      - AUTORESTIC_BACKBLAZE_RESTIC_PASSWORD=${AUTORESTIC_BACKBLAZE_KEY}
      - AUTORESTIC_DROPBOX_RESTIC_PASSWORD=${AUTORESTIC_DROPBOX_KEY}
      - RCLONE_CONFIG_DROPBOX_TOKEN=${RCLONE_DROPBOX_TOKEN}
    command:
      - autorestic
      - --help
