---
- sensor:
    - name: Date
      icon: mdi:calendar
      state: >
        {% set days = ['Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag',
        'Lördag', 'Söndag'] %}
        {% set months = ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni',
        'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'] %}
        {{ days[now().weekday()] }} {{ now().day }} {{ months[now().month-1] }}
