---
- binary_sensor:
    - name: Garage Door
      device_class: garage_door
      state: >
        {% set angle = states("sensor.xiaomi_vibration_0_angle_y") %}
        {% set threshold = states("input_number.garage_door_angle_threshold") %}
        {% if is_number(angle) %}
          {% set angle = angle | float %}
          {% set threshold = threshold | float %}
          {{ angle < threshold }}
        {% else %}
          unknown
        {% endif %}
